Refactoring/optimization
cocoa-mhlw/cocoa pull request #151
Opened 2021-05-04 12:29 UTC by Takym

## Issue 番号 / Issue ID

- #114

## 目的 / Purpose

- 使われていないコードを一部削除しました。
- Android でのみ利用されているクラスを移動しました。
- JSON 関連で冗長な関数を削除しました。

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes) (API は一部変更されています)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone https://github.com/Takym/cocoa
cd cocoa
git checkout refactoring/optimization
dotnet restore
```

### コードの検証 / Test the code

```

```

## 確認事項 / What to check

- [ ] 正しく動作する。

## その他 / Other information
プロジェクトファイルの `DefineConstants` に `REMOVE` を指定するとおおよそ元の状態に戻ります。

2021-05-04 16:45 UTC, keiji reviewed
ありがとうございます。
まず、masterとの違いを確認したいのであればブランチ切り替えで対応できるので、ifディレクティブで切り替え可能にしなくてもいいかなと思いました。

リファクタリングという観点からは、不要な記述は削除してしまった方がすっきりしますし、C#の流儀をよくわかっていないのですが、プリプロセッサディレクティブは可読性を落とすイメージがあり、可能な限り使いたくないという気持ちがあります。

AndroidExtensionsはAndroidでしか使わないのでと言うのはご指摘の通りです。いっそファイル名も`Extensions.cs`に変えてしまってもいいかもしれません。

2021-05-04 17:30 UTC, Takym commented
`#if REMOVED` と `#if !REMOVED` は全て削除し、`AndroidExtensions` は `DiagnosisSubmissionParameter` に対する操作を行っているので `DSPExtensions` に改名しました。`REMOVED` は元のコードに素早く切り替える為に残しておきましたが、不要との事でしたので削除しました。

2021-05-04 18:00 UTC, keiji requested changes
確認しました。
いくつかレビューで指摘しましたが、基本的に不要コードの削除とJsonConvertの展開で挙動やテストの範囲が大きく変わると言ったことはなさそうだなと思いました。

今日あたりにユニットテストと、iOSでのビルドチェックしてみます。

2021-05-04 19:45 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/DSPExtensions.cs
> +    public static class DSPExtensions
始めは `DiagnosisSubmissionParameterExtensions` にしようと思ったのですが、長いので省略しました。確かにコードに影響しませんね。

2021-05-04 19:47 UTC, Takym commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> -        #endregion
ご指摘ありがとうございます。修正しました。

2021-05-04 20:09 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/DSPExtensions.cs
>          public static byte[] GetAndroidNonce(this DiagnosisSubmissionParameter submission)
名前から Android を取り除きました。

`GetKeyString` `GetKeyString` `GetRegionString` `GetSha256` は元々 `private` です（何故か修飾子は省略されていました）。

2021-05-04 20:18 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/DSPExtensions.cs
> +    public static class DSPExtensions
`DSPExtensions` は `DiagnosisSubmissionParameterExtensions` に改名しました。

[refactoring/optimization-dsp](https://github.com/Takym/cocoa/tree/refactoring/optimization-dsp) にて、`DiagnosisSubmissionParameterExtensions` を `DeviceCheckService` に結合しました。必要であれば [refactoring/optimization](https://github.com/Takym/cocoa/tree/refactoring/optimization) に merge します。
https://github.com/cocoa-mhlw/cocoa/blob/5d0d031c496f3cd683766629637f41e299828494/Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs#L21-L25
https://github.com/cocoa-mhlw/cocoa/blob/5d0d031c496f3cd683766629637f41e299828494/Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs#L38-L62

2021-05-05 16:37 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/DSPExtensions.cs
> +    public static class DSPExtensions
たしかに用途を考えれば、拡張関数にする必要はないですね。
5d0d031c496f3cd683766629637f41e299828494 もこのブランチに入れちゃいましょう。

2021-05-05 16:39 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/DSPExtensions.cs
>          public static byte[] GetAndroidNonce(this DiagnosisSubmissionParameter submission)
C#はデフォルトでprivateなんですね！
JavaやKotlinをよく使うので新鮮です。

2021-05-05 16:43 UTC, keiji commented
iOSとAndroidでビルドチェックしました。
将来的にはユニットテストも書きたいですね。

2021-05-05 21:21 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/DSPExtensions.cs
>          public static byte[] GetAndroidNonce(this DiagnosisSubmissionParameter submission)
Java や Kotlin だとアクセス修飾子を省略すると internal になるのですね。

2021-05-05 21:24 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/DSPExtensions.cs
> +    public static class DSPExtensions
マージしました。

2021-05-05 21:34 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/DSPExtensions.cs
>          public static byte[] GetAndroidNonce(this DiagnosisSubmissionParameter submission)
GetKeyString あたりは全てローカル関数にしたので紛らわしさは回避できたと思います。

2021-05-06 01:03 UTC, keiji approved these changes
LGTM

2021-05-14 18:20 UTC, fumiya-kume commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        public static byte[] GetNonce(DiagnosisSubmissionParameter submission)
[質問] `GetNonce` を Public にしている理由は何故ですか？

2021-05-14 19:48 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        public static byte[] GetNonce(DiagnosisSubmissionParameter submission)
元々 `public` だったものをそのまま引き継いだ為です。元は別のプロジェクトに入っていたので `public` になっていたのだろうと思います。また、外部に公開しておけば単体テスト処理も書きやすいでしょう。（この PR はリファクタリングが目的ですので、ここでは単体テストは書いていません）

2021-05-15 06:03 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        public static byte[] GetNonce(DiagnosisSubmissionParameter submission)
せっかく指摘いただきましたし、このあたりはprivateにしておきましょうか。
単体テスト処理を書く必要が出てきたらアクセスコープを見直しましょう。個人的にテストはpublicなメソッドだけで良いと思っているので、DeviceCheckの先をモック化してテストを書くことになるかと思います。

もしこれらのメソッドが壊れやすいもので、テストの柔軟性を最大限確保するなら、このあたりは別のstaticクラスにして置いておくのも一案と思います（それをすると元に戻すことになるのですが…

2021-05-15 06:14 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        public static byte[] GetNonce(DiagnosisSubmissionParameter submission)
`GetNonce` を修正し、付け加えて `GetSafetyNetAttestationAsync` に `private static` を書き加えました。

2021-06-07 08:20 UTC, Takym commented
@cocoa-devさん、@keijiさん、@heykuroさん、@halskさん

https://github.com/cocoa-mhlw/cocoa/pull/210/commits/8052045323e6a54826f04d3d2b705cf775736e1f にて新しいクラス `DateTimeUtility` が作成されています。これはテストの為に作成されたと思われますが、この PR で削除すべきでしょうか？もしくは、別の PR にてサービス化した方が良いのでしょうか？現在はサービスになっておらず、静的変数を書き換える事で他のクラスへインスタンスを注入しています。

2021-06-07 10:25 UTC, Takym commented
https://github.com/Takym/cocoa/tree/refactoring/optimization2 にて更にリファクタリングを行いました。

2021-06-11 02:14 UTC, keiji requested changes
コンフリクトの解消お願いします！

2021-06-11 02:28 UTC, keiji commented
ご指摘の `DateTimeUtility`、テストの時にInstanceを差し替えてダミーの日付を取得するのに使っているんですね。

これはこのままでも動きますが、統一感を考えれば他のServiceと合わせて`mockRepository`から取得する方がきれいですね。ただ、そこまでする必要性があるかと言われると…個人的には迷っていますが、対応するとしても別途にした方が良さそうです。

`optimization2` ありがとうございます。そちらはこのPRに依存がないようであれば別Pull Requestでいきましょう！

2021-06-11 03:06 UTC, Takym commented
#222 にて新しいPRを建てました。

2021-06-11 03:08 UTC, Takym commented
本来は新しく Issue を作成してから言うべきですが、`DateTimeUtility.Instance` は外部から簡単に書き変える事ができるので不具合の原因になりそうです。

2021-06-14 01:11 UTC, keiji commented
コンフリクト解消お願いしますー

2021-06-14 01:44 UTC, Takym commented
解消しました。

2021-07-15 05:03 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        private static async Task<string> GetSafetyNetAttestationAsync(byte[] nonce)
@Takym 
質問のみですが、staticに変えた理由はありますか？

2021-07-15 05:37 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        private static async Task<string> GetSafetyNetAttestationAsync(byte[] nonce)
Visual Studio から `static` にして仮想化呼び出しを避ける様警告されたためです。

2021-07-15 06:26 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        private static async Task<string> GetSafetyNetAttestationAsync(byte[] nonce)
@Takym 
私の環境(Mac)では警告が表示されずどのような意味を持った警告なのかわかりませんでした。
すみませんがその警告がどのような意味か教えていただいてもよろしいでしょうか？

2021-07-15 06:48 UTC, cocoa-dev commented
すみませんがコンフリクトの解消もお願いします

2021-07-15 07:18 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        private static async Task<string> GetSafetyNetAttestationAsync(byte[] nonce)
そのメソッドがクラスのインスタンスに依存しないのであれば、staticを指定することで「インスタンスに依存しないこと」を明示できることに加えて、コンパイラがinline展開できるので実行パフォーマンスが上がったりして都合が良い。という話だと記憶しています。

少し前の情報ですが、それっぽい記事を見つけました。
https://ufcpp.net/blog/2018/12/devirtualization/

2021-07-15 07:18 UTC, Takym commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        private static async Task<string> GetSafetyNetAttestationAsync(byte[] nonce)
`static` を付け静的関数にした場合、コンパイラは直接関数を呼び出す様にコードを生成します。
`static` を外し動的関数にした場合、コンパイラは関数を仮想呼び出しするコードを生成します。

最近の Visual Studio では静的関数に変更できる関数は極力変更するよう警告を出してくれる様になりました。

また、`static` を付ければ動的メンバーを参照しないという意思表示にもなります。

#### 参考
* <https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822>
* <https://ufcpp.net/study/csharp/misc_construct.html>
* <https://ufcpp.net/study/csharp/oo_vftable.html>

2021-07-15 07:39 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs
> +        private static async Task<string> GetSafetyNetAttestationAsync(byte[] nonce)
ありがとうございます
私自身がstaticを積極的に使ってこなかったというのもあり疑問に思ってしまいました。
腹落ちしました。

2021-07-15 07:41 UTC, cocoa-dev approved these changes

2021-07-15 07:42 UTC, Takym commented
コンフリクト解消しました。

2021-07-15 07:43 UTC, keiji approved these changes

2021-07-15 07:43 UTC, merged