Implement migration
cocoa-mhlw/cocoa pull request #165
Opened 2021-05-13 05:08 UTC by keiji

## Issue 番号 / Issue ID

- Close #156

## 目的 / Purpose

アップデート時のメンテナンスコストを低減するため、バージョンアップ（アップデート）時に、特定のバージョンから最新バージョンまでの移行処理を一元的に行う仕組みを用意する。

-

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```

```

## 確認事項 / What to check

-

## その他 / Other information

検証用の実証。
ユニットテストも必要。

2021-05-13 05:42 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/VersionMigrationService.cs
> +namespace Covid19Radar.Services
行数が多い。今後のことを考えるとマイグレーション処理を分割して `Covid19Radar.Services.Migration`を作ってそこに別ファイルで入れるのがよさそう。

2021-05-15 03:49 UTC, keiji commented on Covid19Radar/Tests/Covid19Radar.UnitTests/Services/Migration/VersionMigrationServiceTests.cs
> +}
末尾改行

2021-05-17 10:13 UTC, keiji commented
二日寝かせたらもっといい方法らしきものを思いついたのでやってみる。

2021-05-17 16:01 UTC, keiji commented
もっといい方法というのは、バージョンごとのMigratorをリストに積んで順次実行するものだったのだけど、実際にやろうとしたらうまくいかなかった。
共通処理だけであれば問題ないけど、Platform固有のMigratorを呼ぶとなると処理が複雑になりすぎるので、このままの方が良いという結論に。

2021-06-11 02:12 UTC, keiji commented
しばらく寝かしたらもっといい方法が思い浮かぶかと思ったけどそうでもなかったのでReady for reviewした。

2021-07-11 03:07 UTC, keiji commented
rebased

2021-07-29 07:34 UTC, cocoa-dev requested changes

2021-07-29 07:34 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator122.cs
> +            var result = false;
[修正任意]

```suggestion
            var existsCorruptData = false;
```

2021-07-29 07:34 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator122.cs
> +        public override async Task MigrateAsync()
[修正任意]
アクセス修飾子が大きい順にメソッドを並べていただけると読み下しやすいです。

2021-07-29 07:34 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator122.cs
> +        const string APPLICATION_PROPERTY_USER_DATA_KEY = "UserData";
[修正任意]
定数はメソッドより上にまとめて定義していただきたいです。
少なくとも定数を呼び出しているメソッドよりは上に定義していただけると読みやすいです。

2021-07-29 07:34 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/VersionMigrationService.cs
> +            _loggerService.Debug($"AppVersion: {appVersion}");
[修正任意]
`Debug()` だと CSV のログに出力されないので、センシティブな情報でなければ `Info()` などのメソッドを使うのがいいと思います。
ログに不要と判断して `Debug()` を使っているのであれば修正不要です。

2021-07-29 07:34 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/VersionMigrationService.cs
> +            _loggerService.Debug($"AppVersion: {appVersion}");
他も同様です。

2021-07-29 07:36 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/Migration/Migrator123.cs
> +        private static void CancelOldWorks(WorkManager workManager, string[] oldWorkNames, ILoggerService loggerService)
あ、Xamarin.EN の処理をそのまま移動したためでしたね。
もし static にしなくても動作するなら外していただきたいです。

2021-07-29 07:56 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/Migration/Migrator123.cs
> +        private static void CancelOldWorks(WorkManager workManager, string[] oldWorkNames, ILoggerService loggerService)
以前、別のPRでもstaticの取り扱いについて会話があったのですが、private staticにするとコンパイラ時に関数を展開するなど最適化が効いたりもするので、期待する動作が明確で入力が多くないケースでは、なるべくstaticを使うようにしています。

https://github.com/cocoa-mhlw/cocoa/pull/151#discussion_r670135102

当時 `CancelOldWorks` を作っているときにぼくも意見を出しました。将来的に移動することを考えて、所属しているクラスのメンバ変数に依存しないようにstaticを付ける提案をした覚えがあります。

2021-07-29 07:58 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/VersionMigrationService.cs
> +            _loggerService.Debug($"AppVersion: {appVersion}");
ありがとうございます。
appVersionについてはログの各行に入ってくるものなのでDebugとして、ほかのログについては再検討します。

2021-07-29 08:00 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/Migration/Migrator123.cs
> +    public class Migrator123: IVersionMigrationService
対応します。

当初`FromXXXToYYY`の形式で作っていて、何かのきっかけで現在の形式になったと記憶しています。記憶がはっきりしておらず、今見ると確かに`FromXXXToYYY`の方がわかりやすいですね。対応していく中で理由を思い出したら（その理由が妥当と思えれば）再度コメントしますね。

2021-07-29 08:20 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/VersionMigrationService.cs
> +            _loggerService.Debug($"AppVersion: {appVersion}");
あ、そうですね、常に出力されるので `appVersion` は不要でしたｗ
他のご検討よろしくお願いします。

2021-07-29 08:28 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/Migration/Migrator123.cs
> +        private static void CancelOldWorks(WorkManager workManager, string[] oldWorkNames, ILoggerService loggerService)
リンクのご共有ありがとうございます。static の取り扱いについて理解できました。
オブジェクト指向の言語では static を避けたくなりますが、インスタンスに依存しないことを保証できるので、むしろ使える場面では積極的に使うべきなのかもしれませんね。

2021-07-29 09:05 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/Migration/Migrator123.cs
> +        private static void CancelOldWorks(WorkManager workManager, string[] oldWorkNames, ILoggerService loggerService)
static メソッドから変更しないので、引数で渡す必要がありますね。
解決とします。

2021-07-30 01:08 UTC, keiji commented
ひとまずconflictを解消

2021-07-30 05:13 UTC, cocoa-dev commented
@keiji 
簡単でいいのでマイグレーション処理の内容を PR の概要に記載していただくことは可能でしょうか？

2021-08-17 06:57 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/Migration/Migrator123.cs
> +    public class Migrator123: IVersionMigrationService
思い出しました。これはFromのバージョンは複数があり得るので、厳密に指定しない方がいいと考えたからでした。

たとえば当初は`From100To122`のようにしていたのですが、実際には`1.0.0`と`1.2.2`までの間には、いくつものバージョンがあります（`v1.1.0`, `v1.1.1`,  `v1.1.2`, `v1.1.3`, `v1.1.4`, `v1.1.5`, `v1.2.0`, `v1.2.1`）。

https://github.com/cocoa-mhlw/cocoa/releases

マイグレーションの条件式は、「現在バージョンが1.2.2より小さければ」のようになるので、クラス名やメソッド名にFromの要素を入れることで間違ったメッセージ（From100To122であればv1.0.0からv1.2.2の場合だけマイグレーション処理を行う）として伝わってしまうなと考えてFrom…については削ったという経緯があります。

2021-08-17 06:58 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator122.cs
> +            var result = false;
done

2021-08-17 06:59 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator122.cs
> +        public override async Task MigrateAsync()
done.

2021-08-17 06:59 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator122.cs
> +        const string APPLICATION_PROPERTY_USER_DATA_KEY = "UserData";
done.

2021-08-17 07:37 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/VersionMigrationService.cs
> +            _loggerService.Debug($"AppVersion: {appVersion}");
特にマイグレーションの経過として記録が必要と思われるものをInfo, Warningに置き換えました。

2021-08-29 12:44 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +        private async Task MigrateAsync(Version? fromVersion)
とはいえ色のつく警告を放置は気持ち悪いので、クラスファイルの最初と最後に`#nullable enable/disable`で対応しました。

2021-08-29 12:46 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +            var currentVersion = CurrentAppVersion;
CurrentAppVersionはアプリのバージョンなので固定でした。
コンストラクタからEssentialServiceを使うとエラーが起きてスタックすることがわかったので、呼び出しのときに変数を取って使い回すようにしてあります。

`UpdateAppVersionPreference`もわかりにくかったのでSet/Getの組み合わせのメソッドを用意しました。

2021-08-29 12:49 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs
> +            await _migrationService.MigrateAsync();
こう書きましたが、中身を見たらちゃんとセマフォ取ってました。

Singletonなのでバックグラウンド処理とUI・アップデート処理でMigrationServiceは同じインスタンスになり、セマフォが解放されるまで待つことになります。
内部でTask.Delayしてみたところ、バックグラウンド処理（WorkManager）でのマイグレーション処理の実行中、Splashスクリーンで待機して、その後ホーム画面に遷移することが確認できています。

現状、マイグレーション処理は長くても1秒程度で終わるので無視できる程度だと思いますが、マイグレーション処理が長くなればSplash画面になんらかの表示をすることを検討した方が良さそうです。

2021-08-29 12:50 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +
ダウングレードは考慮しないとしたので、この部分の処理は削除しました。
（Gitの履歴には残っているので、何かあれば復活はできます）。

2021-08-29 12:53 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +    public abstract class AbsMigrationService
はい。元々はこのクラスにいくつかのデフォルト実装を入れてあったのですが、いまではMigrateAsyncだけになっているいまはabstract classである意味は無いですね。interfaceにして名前も`IMigrationService`にしました。

ちなみに`Abs`はJavaだとabstract classを示す接頭辞としてよく出てくるのですが、いま調べた限りC#ではそういうことはしないんですね…。

2021-08-29 12:56 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/Migration/MigrationProcessService.cs
> +    {
記載しました！

2021-08-29 13:01 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +                    return null;
見逃してました。
変更は反映してあります（ 83b8324 ）。

2021-08-30 00:47 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/Migration/WorkManagerMigrator.cs
> +            };
こちら内容が変わってしまっていますのでご対応をお願いします。

![image](https://user-images.githubusercontent.com/69558847/131271208-7edfdf8a-d207-4956-abf3-3869c6fdd790.png)

2021-08-30 01:56 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/Migration/WorkManagerMigrator.cs
> +            };
そうか……この間のsyncでここ変わったんですね。対応します！

2021-08-30 02:14 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +        private Task<bool> DetectDowngradeAsync()
ダウングレードなしで行くことになったので、このメソッドは削除になりました。

2021-08-30 02:14 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +            fromVersion = fromVersion is null ? GuessVersion() : fromVersion;
Done

2021-08-30 02:14 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +                var appVersion = _preferencesService.GetValue<string>(PreferenceKey.AppVersion, FIRST_VERSION);
Done

2021-08-30 02:47 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/MigrationService.cs
> +    public abstract class AbsMigrationService
経緯の説明とインターフェースへの変更ありがとうございます！
以下のコミットで問題ないことを確認したので Resolved にします。
https://github.com/cocoa-mhlw/cocoa/pull/165/commits/fb2711b263474fd5e282fcaabb810739502b4933

`Abs` は Java だとよく出てくるのですね…。
もしかしたら C# でも使われるかもしれませんが、私は知りませんでした、、

2021-08-30 02:52 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs
> +            await _migrationService.MigrateAsync();
ご確認ありがとうございます。
マイグレーションのテスト時にあまりにも長く感じたら、インジケータの表示などを検討すればいいと思うので、こちらは解決とします。

2021-08-30 03:11 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_2_2.cs
> +            userDataModelForFailback.StartDateTime = DateTime.Now.ToString();
こちらのコードは基本的に通らないかもしれませんが、UtcNowを使用するのが適切かと思います。

2021-08-30 03:38 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_2_2.cs
> +            userDataModelForFailback.StartDateTime = DateTime.Now.ToString();
ありがとうございます。
GBロケールで初期化後、JPロケールに変更した状態でアップグレードを迎えると通る経路ですね。

このPull Requestを作った後に、Cultureを指定して日時をパースできることを覚えたので、GBロケールで読み込み直しというのも入れてみたいところですが、そこは別Pull Requestにします。

2021-08-30 03:40 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_2_2.cs
> +            userDataModelForFailback.StartDateTime = DateTime.Now.ToString();
StartDateTimeについては、既存の初期値がUtcNowを使用しています。デグレになってしまいますので対応をお願いしたいです。念の為既存の初期値も見ていただければと思います。

2021-08-30 05:05 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_2_2.cs
> +            userDataModelForFailback.StartDateTime = DateTime.Now.ToString();
UtcNowには修正していただいていましたね。失礼しました。

2021-08-30 05:05 UTC, cocoa-dev approved these changes

2021-08-30 08:55 UTC, merged