Issue#160
cocoa-mhlw/cocoa pull request #178
Opened 2021-05-14 16:12 UTC by i-maruyama

## Issue 番号 / Issue ID

- Close #160

## 目的 / Purpose

-

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

- Debug_Mock ビルドでの実行テスト
- Release ビルドには影響しないことのチェック（コードレビューレベルで良い）

プロプロセッサによって Release ビルドでは、メニューに表示されません。

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

1. Debug_Mock ビルドで実行します。
2. メニューからデバッグページを選択
3. 情報やボタンがあることを確認
4. リロードやナビゲーションが動くことを確認

```

```

## 確認事項 / What to check

- 機能ボタンは、主に SettingsPageViewModel.cs から取ってきているだけで、もともとユーザーが実施可能であったものです。
- ナビゲーションは、主に App.xaml.cs から取ってきているだけですが、 SplashPage などもとは到達不可能なページが含まれます。
- いくつかの機能は、現状の Debug_Mock では不十分です。

## その他 / Other information

スクリーンショットを #160 に貼っておきます。

2021-05-14 16:46 UTC, fumiya-kume commented
[提案] PR のタイトルをPRの内容を説明したものに変更してみませんか？

2021-05-14 16:48 UTC, i-maruyama commented
ありがとうございます。変更しました。（まだ慣れてません）

2021-05-14 18:06 UTC, fumiya-kume commented on Covid19Radar/Covid19Radar/Views/HomePage/DebugPage.xaml
> +            <Frame
[重箱の隅突き] Button をリスト表示するなら、ListView を使って実装するのも良さそう。
https://docs.microsoft.com/ja-jp/dotnet/api/xamarin.forms.listview?view=xamarin-forms

2021-05-14 18:12 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +    public class DebugPageViewModel : ViewModelBase
このページだけのディレクトリを作るのは避けたいのですが、既存のもの(HelpPage, Settings..)だとどれが良いでしょうか？現状のページ配置も、それほど意味を見出せないのですが・・

・・・と、私は悩んで、どれでもいいかとなってしまっています。

2021-05-14 18:22 UTC, fumiya-kume commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +    public class DebugPageViewModel : ViewModelBase
DebugはDebugというだけでドメインが違うので単体でフォルダを切る価値があると思いました。
下手にフォルダの中に入れるのではなく、Viewの直下においても良いかもですね。

>現状のページ配置も、それほど意味を見出せないのですが・・
それな...

2021-05-14 18:45 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +            switch (Device.RuntimePlatform)
この switch 文が別ファイルにあったので、安全のためそれに倣いました。将来を考えて、 default を付けています。

2021-05-14 18:45 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Views/HomePage/DebugPage.xaml
> +    xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
安全のための HomePage.xaml からの流用です。とりあえず,このまま同じにしておきますので、一斉除去する機会に掃除してください。

2021-05-14 18:49 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +    public class DebugPageViewModel : ViewModelBase
もし開発チームに意向があれば反映する、という方針にして、ここは見えるようにおいておきます。

2021-05-14 18:59 UTC, i-maruyama commented
ありがとうございました。一応エミューレータの再起動を確認してプッシュしました。

2021-05-15 10:51 UTC, fumiya-kume commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +            switch (Device.RuntimePlatform)
こちらの8個目にあるように必要以上に安全な振りすぎてると思いますが、どうでしょう？

https://medium.com/edge-coders/the-mistakes-i-made-as-a-beginner-programmer-ac8b3e54c312

2021-05-15 10:52 UTC, fumiya-kume commented on Covid19Radar/Covid19Radar/Views/HomePage/DebugPage.xaml
> +            <Frame
解決済み🤔

2021-05-15 14:35 UTC, keiji commented on Covid19Radar/Covid19Radar/Views/HomePage/DebugPage.xaml
> +    xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
ここはVisual Studioさんも指摘している箇所なので、適宜（次に何か手を加えるタイミングででも）消しておいてもらえるとうれしいです！（見落としが発生するかもしれないので、いったんUnresolveにしておきますね。

<img width="781" alt="Screen Shot 2021-05-15 at 23 21 44" src="https://user-images.githubusercontent.com/932136/118364662-5d6c3980-b5d4-11eb-8844-2c19634b0bc7.png">

ちなみに、開発に参加している人たちがお互いのコードを確認して、気がついたことを指摘する行程をコードレビューと言います。オープンソースでは一般的で、コードをよりよいものにすることを目的としていて、コードの欠点を見つけることは目的としていないのでご安心ください。

コードレビューはコミッター（コードの取り込みを決定する権限のある人）だけでなく、コントリビューター相互で行われる場合があります。

大きいPull Requestだとコードレビューで出てくる指摘も多くなりますし、指摘と修正のやりとりにかかる期間も長くなります。コミッターからの指摘に応じてすぐに直してもらっても、次に同じPull Requestを見るまで期間が空いてしまったりします。なので、さまざまなコントリビューターにレビューに参加してもらえているのは本当にありがたい限りです。

2021-05-15 14:40 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +            UserDialogs.Instance.ShowLoading("Starting ExposureNotification...");
UserDialogsのInstanceを使っているのは`Acr.UserDialogs`（外部イブラリでCOCOAの範疇外という認識）の通常の使い方のようです。

指摘の意図としては、UserDialogsのInstanceを一旦、IUserDialogsのプロパティやメンバ変数としてクラスに持った方がいいということでしょうか。InstanceがSingletonであればこのままでもいいような気がします。

2021-05-15 14:46 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +            switch (Device.RuntimePlatform)
ここはもう、次のようにまとめてしまうのでどうでしょう。iOSとAndroid以外への対応は、要件が出てきたときに考えましょう。

```
            string os = Device.RuntimePlatform;

#if USE_MOCK
            os += ",USE_MOCK";
#endif
```

ちなみに、このページは`DEBUG`が有効の時にしか見えないものなので、`if DEBUG`はなくてもいいかなと思いました。

2021-05-15 14:51 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +    public class DebugPageViewModel : ViewModelBase
これは要検討ですね。
itemGroupのような仕掛けでReleaseビルドに含めないようにするのなら、1つのディレクトリ（たとえば`DebugPage`など）に集約されていることに意味はあると思います。

一方で、今の名前空間が`View`や`ViewModel`といった分け方なので、そこにいきなり機能単位の`DebugPage`が来るのは違和感が拭えません。

となると、`View/DebugPage`と`ViewModel/DebugPage`のようにするのが納得感がある反面、ディレクトリが深くなっただけで1つのファイルしか保存していないなら今のままでいいじゃないかという…

まずはここは課題として残しておき、機能面やその他の場所を見ていきましょう。どこに配置するかは頃合いを見て決めると言うことで。

2021-05-15 14:52 UTC, keiji commented on Covid19Radar/Covid19Radar/Views/HomePage/DebugPage.xaml.cs
> + * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
ライセンスﾖｼｯ!

2021-05-15 14:52 UTC, keiji commented on Covid19Radar/Covid19Radar/Views/HomePage/DebugPage.xaml
> +    - file, You can obtain one at http://mozilla.org/MPL/2.0/. -->
ライセンス通知ﾖｼｯ!

2021-05-15 14:52 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> + * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
ライセンス通知ﾖｼｯ!

2021-05-15 16:49 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +            switch (Device.RuntimePlatform)
多数決で、
```
     string os = Device.RuntimePlatform;
```
にします。
あと、 if DEBUG はつけておきたいのですが良いでしょうか？手元では、 Release ビルドも実施しているので。

2021-05-15 16:50 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +            string LastProcessTekTimestamp = dt.ToLocalTime().ToString("F");
修正しました！

2021-05-15 16:52 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +            var status = await exposureNotificationService.UpdateStatusMessageAsync();
修正しました。https://github.com/cocoa-mhlw/cocoa/pull/178/commits/e9bd943395695a38a310f155356c2972ce2bace7

2021-05-15 16:52 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +            var en = await Xamarin.ExposureNotifications.ExposureNotification.IsEnabledAsync();
修正しました。https://github.com/cocoa-mhlw/cocoa/pull/178/commits/e9bd943395695a38a310f155356c2972ce2bace7

2021-05-15 17:25 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Views/HomePage/DebugPage.xaml
> +    xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
こちら初心者（GitHubも）でして、お手数ですが Resolve　/　Unresolve も適宜お願いいたします。

この部分については、HomePage からの流用であっても xmlns:ffimageloading は不要ですね。（今のDebugPage は画像を使っていないので）
そういうご指摘だったということを今理解しました。なので一つ上の私の解答は、的外れです。

おかげさまで今回、驚くことや学ぶことは多く、皆さんに感謝しています。(迅速なレビューとGitHub PR上のコミット、オンラインの実行テストなど）

2021-05-16 05:33 UTC, Takym commented
https://github.com/i-maruyama/cocoa/pull/1 にて `Release` ビルド時にデバッグページを除外する為の設定をプロジェクトファイルに追加しました。

2021-05-16 05:38 UTC, Takym commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +    public class DebugPageViewModel : ViewModelBase
参考までに、元々あったデバッグページは設定ページと同じディレクトリに置いてありました。
https://github.com/cocoa-mhlw/cocoa/tree/4c4aca39b02dcb1bd89569674b65b0ef6a357bae/Covid19Radar/Covid19Radar/Views/Settings

同じ場所に置くと GitHub の History ボタンから履歴が見やすくなると思います。

2021-05-16 05:44 UTC, Takym commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +        public async void info(string ex = "")
他にも、COCOAでは公開関数の名前は大文字から始める様になっています(僕はそう認識しています)ので、そちらに合わせるべきでしょう。

2021-05-16 12:47 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/DebugPageViewModel.cs
> +    public class DebugPageViewModel : ViewModelBase
> 同じ場所に置くと GitHub の History ボタンから履歴が見やすくなると思います。

少なくとも HomePage/ よりは、まともな根拠と思いますので、Settings/ に変えたいですね。

2021-05-16 13:02 UTC, i-maruyama commented
> [i-maruyama#1](https://github.com/i-maruyama/cocoa/pull/1) にて `Release` ビルド時にデバッグページを除外する為の設定をプロジェクトファイルに追加しました。

このようにするのですね。ありがとうございます。取り込みます。
ただ申し訳ないことにこちらの力不足で、 Release ビルドで正しく削除されたかの確認方法が分かりません。

2021-05-16 14:51 UTC, fumiya-kume commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            string lastProcessTekTimestamp = dt.ToLocalTime().ToString("F");
```suggestion
            var lastProcessTekTimestamp = dt.ToLocalTime().ToString("F");
```

2021-05-16 14:51 UTC, fumiya-kume commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            DateTimeOffset dt = DateTimeOffset.FromUnixTimeMilliseconds(ticks).ToOffset(new TimeSpan(9, 0, 0));
```suggestion
            var dt = DateTimeOffset.FromUnixTimeMilliseconds(ticks).ToOffset(new TimeSpan(9, 0, 0));
```

2021-05-16 14:51 UTC, fumiya-kume commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            long ticks = exposureNotificationService.GetLastProcessTekTimestamp(AppSettings.Instance.SupportedRegions[0]);
```suggestion
            var ticks = exposureNotificationService.GetLastProcessTekTimestamp(AppSettings.Instance.SupportedRegions[0]);
```

2021-05-22 08:37 UTC, Takym commented
> > [i-maruyama#1](https://github.com/i-maruyama/cocoa/pull/1) にて `Release` ビルド時にデバッグページを除外する為の設定をプロジェクトファイルに追加しました。
> 
> このようにするのですね。ありがとうございます。取り込みます。
> ただ申し訳ないことにこちらの力不足で、 Release ビルドで正しく削除されたかの確認方法が分かりません。

返信が遅れて申し訳ありません。
Visual Studio からビルド構成を `Release` に変更するとソリューションエクスプローラからデバッグページ関連のファイルが見えなくなります。ソリューションエクスプローラにはコンパイルするファイルのみ表示されますので、除外されている事が確認できます。

2021-05-25 12:53 UTC, i-maruyama commented
> Visual Studio からビルド構成を `Release` に変更するとソリューションエクスプローラからデバッグページ関連のファイルが見えなくなります。ソリューションエクスプローラにはコンパイルするファイルのみ表示されますので、除外されている事が確認できます。

確認しました。Covid19Radar.csproj へのPRをマージして、現在のディレクトリ Settings に変更しました。

2021-05-26 01:28 UTC, Takym commented
確認しました所、下記の２点が気になりました。

* [Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj](https://github.com/cocoa-mhlw/cocoa/pull/178/files#diff-ed4334d1a32586df68db843e3986da17d8f79ee28fcbe935dae8e1312c5aab04) に意味の無い変更が含まれています。競合を避ける為に元に戻しておくべきだと思います。
* リソースファイルからライセンス通知が取り除かれてしまっています。ファイルが多いので大変ではありますが、元に戻しておくべきでしょう。

2021-05-26 12:35 UTC, i-maruyama commented
> 確認しました所、下記の２点が気になりました。

ありがとうございました。完全にミスしたコミット(１ファイルだけステージングするのを忘れて、
全ファイルコミットしてしまいました）
https://github.com/cocoa-mhlw/cocoa/pull/178/commits/857bc1c720f587671947100c6bf385de05f12253
をリバートし、再度ディレクトリ名だけ変更した１ファイルをコミットしなおしています。

> リソースファイルからライセンス通知が取り除かれてしまっています。

これもご確認ありがとうございました。（ #182 と似た感じでしょうか？）

再度まとめると、もともと https://github.com/cocoa-mhlw/cocoa/pull/178/commits/8fbbc101dd72b86fa4856d5e0bcd7e7eeb2b58e7 では、
変更ファイルは５つでした。

これに、 @Takym さんから PR された Covid19Radar.csproj への変更をマージし、
現在は、６つのファイルが変更されていることになります。

2021-06-07 23:24 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +                "DaysOfUse: " + userDataService.GetDaysOfUse(), "ExposureCount: " + exposureNotificationService.GetExposureCountToDisplay(),
v1.2.4 に対応するため、GetExposureCountToDisplayにしました。

2021-06-09 12:54 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/MenuPageViewModel.cs
> +                Icon = "\uf013",
本質的ではないのですが、虫Icon があるようですね。そちらにしたくなってきました。

2021-06-09 12:54 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            var str = new[] { "Build: " + os, "Ver: " + AppSettings.Instance.AppVersion,
setting.json から設定される <!--StartFragment-->AppSettings.Instance.AppVersion,Write&nbsp;<!--EndFragment--> は、意味のない情報のようで、ログや、バージョンチェックで使われるのは,　EssentialsService.AppVersion のようですね。
何を表示させるか？は、もう少し議論が必要だと思います。

2021-07-05 12:57 UTC, keiji commented
@i-maruyama Pull Requestの向き先を`feature/debug_page`に変えてもいいですか？

2021-07-06 11:57 UTC, i-maruyama commented
お願いします。

2021-07-06 12:58 UTC, keiji commented
向き先変えました！　お手数ですがコンフリクトの解消お願いします！

2021-07-12 01:44 UTC, keiji requested changes
`Debug_Mock`でテストしました。
各ページを直接表示する機能はデザイン調整などに威力を発揮しそうですね。

**追記**
コンフリクトの解消もお願いします。

<img width="785" alt="Screen Shot 2021-07-12 at 10 35 25" src="https://user-images.githubusercontent.com/932136/125218386-d69abb00-e2fd-11eb-9873-9fffc8f3f3d4.png">

<img width="785" alt="Screen Shot 2021-07-12 at 10 35 30" src="https://user-images.githubusercontent.com/932136/125218403-e1555000-e2fd-11eb-905c-eecb6a3f1313.png">

<img width="785" alt="Screen Shot 2021-07-12 at 10 35 35" src="https://user-images.githubusercontent.com/932136/125218411-e5816d80-e2fd-11eb-8bb4-e71c855a129c.png">

<img width="785" alt="Screen Shot 2021-07-12 at 10 35 46" src="https://user-images.githubusercontent.com/932136/125218446-faf69780-e2fd-11eb-91f7-5d518d939032.png">

<img width="785" alt="Screen Shot 2021-07-12 at 10 35 51" src="https://user-images.githubusercontent.com/932136/125218455-0053e200-e2fe-11eb-83dd-df591e285d4e.png">

<img width="785" alt="Screen Shot 2021-07-12 at 10 35 51" src="https://user-images.githubusercontent.com/932136/125218463-05b12c80-e2fe-11eb-80cd-f5b202787695.png">

<img width="785" alt="Screen Shot 2021-07-12 at 10 35 56" src="https://user-images.githubusercontent.com/932136/125218484-0a75e080-e2fe-11eb-8613-1eb67ad63458.png">

<img width="785" alt="Screen Shot 2021-07-12 at 10 36 00" src="https://user-images.githubusercontent.com/932136/125218499-0ea1fe00-e2fe-11eb-8a6b-6317acbdda90.png">

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            var lastProcessTekTimestamp = dt.ToLocalTime().ToString("F");
`GetLastProcessTekTimestamp`で得た値なので`ticks`より`lastProcessTekTimestamp`の変数に入れた方が良いと思います。あとの`lastProcessTekTimestamp`については`DateTime`を意味しているので`lastProcessTekDateTime`とするのはどうでしょうか。

また、取得した日時に対して`ToOffset`で9時間ずらしているようですが、これは後段の`ToLocalTime()`で足りるような気がします。

```
            var lastProcessTekTimestamp = exposureNotificationService.GetLastProcessTekTimestamp(AppSettings.Instance.SupportedRegions[0]);
            var lastProcessTekDateTime = DateTimeOffset.FromUnixTimeMilliseconds(lastProcessTekTimestamp).ToLocalTime().ToString("F");
```

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            var str = new[] { "Build: " + os, "Ver: " + AppSettings.Instance.AppVersion,
表示するのは`EssentialsService.AppVersion`にしましょう。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +        public DebugPageViewModel(INavigationService navigationService, IUserDataService userDataService, ITermsUpdateService termsUpdateService, IExposureNotificationService exposureNotificationServ
横に長くなっているので適切に改行＋インデントをお願いします。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            Title = "Title:DebugPage";
```suggestion
            Title = "Title:Debug";
```

Debug Pageでも良いかと思いましたが、開発者しか使わないことを考えると、よりシンプルに`Debug`でいいかと思います。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +        public async void Info(string ex = "")
メソッド名は動詞から始めてください。また、`async`キーワードがついている場合は接尾辞に`Async`を付けてください。

今回の場合、表示する情報を更新する役割のメソッドなので`UpdateInfoAsync`でいかがでしょうか。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            var exLog = "FetchExposureKeyAsync";
`exLog`の接頭辞`ex`は略さず`exception`と書いた方がわかりやすいです。

また、Logもログを取ることに使っていないので付ける必要はなく、この変数名はシンプルに`exception`で良いと思います。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            await UserDialogs.Instance.AlertAsync(str, str, Resources.AppResources.ButtonOk);
アラートダイアログのタイトルと内容に同じ文字列を表示する意味はないと思います。
タイトルを`StartExposureNotification`、内容を`Result: True or False`としてはいかがでしょうか。

そうれば、ローカル変数strに値を取る必要もないと思います。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            await UserDialogs.Instance.AlertAsync(str, str, Resources.AppResources.ButtonOk);
ここも`OnClickStartExposureNotification`と同様に、アラートダイアログのタイトルと内容に同じ文字列を表示する意味はないと思います。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +        public async void Info(string ex = "")
引数名`ex`は何を意味していますか？ 略称ではなく、実態に沿った名前にしてもらえるとわかりやすくてありがたいです。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            }
`Device.RuntimePlatform`をそのまま使えば、OSプラットフォームの文字列をとることができます。Windowsとかも入ってしまいますが、そもそもビルドできないので考慮しなくて良いと思います。

```suggestion
            string os = Device.RuntimePlatform;
```

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/Settings/DebugPageViewModel.cs
> +            var str = new[] { "Build: " + os, "Ver: " + AppSettings.Instance.AppVersion,
文字列連結は + ではなく、`$`を付けた変数を展開する記法を使ってください。
`$"Build: {os}, Version: {EssentialsService.AppVersion}"` のようになります。

あと、`Ver`は`Version`にするなど、短い単語であれば可能な限り略称を使わないようにしてください。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
> +                    Text="DebugPage" />
DebugPageからDebugPageを開けるのはあまり意味がないと思うので、削除してください。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
> +                    Text="NavigationPage" />
ドロワーがある空白のページが開くだけなので削除して良いと思います。

2021-07-12 01:44 UTC, keiji commented on Covid19Radar/Covid19Radar/Views/Settings/DebugPage.xaml
> +                    Text="MenuPage" />
タップしても何も起きないので、削除して良いと思います。

2021-08-20 04:59 UTC, keiji commented
@i-maruyama 
お忙しいようであればこちら引き取りますがいかがですか？

2021-08-22 23:17 UTC, i-maruyama commented
申し訳ありません。こちらのVisualStudio にエラーがでる状態が解消できずにおりますので、
引き取っていただけるとありがたいです。

頂いているレビューコメントも、おっしゃっている方向で変更することに同意いたします。

2021-09-02 05:57 UTC, keiji commented
@i-maruyama コンフリクト解消のためのPull Requestを出しました。

https://github.com/i-maruyama/cocoa/pull/2

このPRをマージいただいた後、このPRを`feature/debug_page`に取り込んで、そこからさらに作業をする予定です。

2021-09-02 06:08 UTC, merged