update COPYRIGHT THIRD PARTY SOFTWARE NOTICES.
cocoa-mhlw/cocoa pull request #184
Opened 2021-05-16 15:24 UTC by tatsu-jp

## Issue 番号 / Issue ID

- Close #130 

## 目的 / Purpose

ライセンス内容を確認して記述不足や文字化けを修正することで、ライセンス内容を最新の状態にします。

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

## 確認事項 / What to check

- GitHubのビューアで開いて、文字化け等が解消されていることを確認

## その他 / Other information

- https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-841819528 にあるように、Noto Sans CJKのCopyright HolderはAdobeです。
@keiji さんに確認していただきました。
- ©はUTF-8で、Unicode(U+00A9)で表示可能なエディタやビューアでは文字化けが入っているように見えます(参考：https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-841800774 )。環境に依存しない記述へ変更しました。

参考
- https://github.com/googlefonts/noto-fonts/blob/main/LICENSE (SIL Open Font License 1.1)
- https://github.com/googlefonts/roboto/blob/main/LICENSE (Apache License 2.0)
- https://github.com/google/material-design-icons/blob/master/LICENSE (Apache License 2.0)

2021-05-16 15:42 UTC, daisukekoba commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +Licensed under the Apache License, Version 2.0 (the "License");
Apache Licenseへ変更するのではなく、フォントを追加した当時のライセンスであるSILの本文を追加する修正が正しいはずです。

2021-05-16 15:56 UTC, tatsu-jp commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +Licensed under the Apache License, Version 2.0 (the "License");
ご指摘ありがとうございます。すみません、時系列を勘違いしていました。
修正しました。Copyright Holderは[google/material-design-icons](https://github.com/google/material-design-icons)に"Material design icons is the official icon set from Google. "とあったので、Googleにしています。

2021-05-16 16:59 UTC, keiji commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +Licensed under the Apache License, Version 2.0 (the "License");
COCOAで使われているMaterial Design Iconsは https://github.com/Templarian/MaterialDesign-Webfont からのもので、Copyright Holderが Austin Andrews 氏になっているのはそのためと思われます。
ここは原文通り、`2014, Austin Andrews (http://materialdesignicons.com/)` でお願いします。

2021-05-16 22:15 UTC, tatsu-jp commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +Licensed under the Apache License, Version 2.0 (the "License");
ありがとうございます。理解が不十分でした。
今夜修正します。

2021-06-10 16:32 UTC, keiji commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
>  ---
v1.2.4 でNoto Sans CJK JPは削除されたので、合わせてエントリーの削除お願いします:bow:

2021-06-10 16:34 UTC, keiji requested changes
カスタムフォント廃止に伴い、ライセンスの削除が発生しています。
よろしくお願いします。

2021-06-10 16:34 UTC, keiji commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
>  ## (Font) Noto Sans CJK JP
v1.2.4 でNoto Sans CJK JPは削除されたので、合わせてエントリーの削除お願いします:bow:

2021-06-12 08:02 UTC, tatsu-jp commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
>  ## (Font) Noto Sans CJK JP
#210 で削除されていることを確認して、Noto Sans CJK JPのライセンス記述を削除しました。
Info.plist上の指定も削除した方が良いように思うのですが、残している意図等あれば教えて頂けると助かります。

https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.iOS/Info.plist#L60-L67

2021-06-12 08:13 UTC, tatsu-jp commented
#116 (Font Awesome, Robotoの削除)に関してv1.2.4で実施済みとコメントありましたが、#210 では削除されていることを確認できませんでした。develop/mainブランチのCovid19Radar.iOS以下にフォントファイルが残っていました( #116 の修正が反映されていない)。

内部リポジトリ側では修正済み、GitHub側にマージする際に不備があったと理解すれば良いでしょうか。
ご確認お願いします。

2021-06-12 08:24 UTC, keiji commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
>  ## (Font) Noto Sans CJK JP
おそらく消し忘れですね。ありがとうございます。
あとでIssueにします！

2021-06-12 08:25 UTC, keiji commented
Font Awesome, Robotoは削除していません。今回使用をしなくなったのはNoto Sans CJK JPだけなので、削除するライセンスもNoto Sans CJK JPに関するものだけという認識です。

2021-06-12 08:26 UTC, tatsu-jp commented
ご確認ありがとうございます！
了解しました。

2021-06-13 00:30 UTC, keiji approved these changes
LGTM

2021-07-06 02:17 UTC, merged