Issue#179
cocoa-mhlw/cocoa pull request #191
Opened 2021-05-17 12:50 UTC by i-maruyama

## Issue 番号 / Issue ID

- Close #179

## 目的 / Purpose

#179 の実装

-

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

後で書きます

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```

```

## 確認事項 / What to check

-

## その他 / Other information

2021-06-11 05:02 UTC, keiji requested changes
レビューしました！

async/awaitの必要のないところでTaskになっている箇所が見受けられるので、また次のフェーズで確認と調整をしたいです。

2021-06-11 05:02 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +					info.Add(new ExposureInfo(DateTime.UtcNow.AddDays(-d[i++]), TimeSpan.FromMinutes(d[i++]), d[i++], d[i++], (Xamarin.ExposureNotifications.RiskLevel)d[i++]));
`ExposureInfo`の第一引数は`daysSinceLastExposure`と経過した日数を与えるものと理解しています。一方、ここでは現在の日時から`daysSinceLastExposure`を引いた日時を与えているので、実際の接触確認APIから得られる値と齟齬が生まれるのではないかと思うのですが、一度確認をお願いできないでしょうか。

また、ここも同様にインデックスを定数化した上で、実際の配列を参照するときに現在の`index`を加算して参照するのが良いと思います。

2021-06-11 19:16 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private async Task<string> GetCdnAsync(string url, CancellationToken cancellationToken)
取り込みます。

2021-06-11 19:16 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +                downloadClient = httpClientService.Create();
取り込みます。

2021-06-11 19:21 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +            await result.Content.ReadAsStringAsync();
手元では動くのですが、オリジナルがことごとくこのコーディングです・・・

私も知りたいです。
https://github.com/cocoa-mhlw/cocoa/issues/199#issuecomment-850731963

ともかくここは、Mock としてはオリジナルをコピーするのが吉と思います。

2021-06-11 19:22 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private TemporaryExposureKeyExportFileModel TestDat(long created)
CreateTestData にします。

2021-06-11 19:29 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private long TimeBefore(int day)
CalcTimeAddDays, CalcNightTimeAddDays に変更しました。

2021-06-11 19:56 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +            if (dataVer >= 100)
// HttpStatusCode >=100 by RFC2616#section-10 とコメントしました。
https://developer.mozilla.org/ja/docs/Web/HTTP/Status　です。

2021-06-11 19:57 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +            return (new DateTimeOffset(DateTime.UtcNow.ToLocalTime().AddDays(day)).ToUnixTimeMilliseconds());
了解です。

2021-06-11 20:00 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private long NightBefore(int day)
CalcMidnightTimeAddDays にしました。

2021-06-11 20:04 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +            return (new DateTimeOffset(new DateTime(d.Year, d.Month, d.Day, 0, 1, 2, 3)).ToUnixTimeMilliseconds());
LocalTime をはずし、
// set 0 hour,1 min,2 sec,3 millisecond for debug
と追記しました。

2021-06-11 20:05 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private List<TemporaryExposureKeyExportFileModel> DataPreset(int dataVer)
dataVersion　にします。

2021-06-11 20:06 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private static bool DownloadRequired()
IsDownloadRequired  にします。

2021-06-11 20:12 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +            else if (Regex.IsMatch(url, @"^(\d+,)+\d+,*$"))
IsDirectInput　というのを追加しました。
 "1598022036649,1598022036751,1598022036826" -> direct input timestamps 
にもコメント追加しました。

デバッグ系をまとめるとき、手順書を書く必要がありますね。

2021-06-11 20:21 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private ushort NumberEndofSentence(string url)
では、共通クラスは、TestNativeImplementation.cs のファイルにおき、
```
namespace Covid19Radar.Services
{
   class MockCommonUtils // common to TestNative HttpDataServiceMock 
```
のように、Covid19Radar.Services　の下に配置する方向で良いでしょうか？

2021-06-11 20:24 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +                case 1:
先ほどの共通クラス内で UrlApiRegister　という関数にします。

2021-06-11 20:27 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +		private ushort[] DataPreset(int dataVer)
dataVersion にしておきます。今後、誰かが新しいバージョンのプリセットデータを作っていくという気持ちです。

2021-06-11 20:42 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +				case 1:
取り込みます。

2021-06-11 20:48 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +		public string[] UrlApi()
GetUrlPathSegments にします。

2021-06-11 21:00 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +			var urlApi = url;
/r, /d は文字列抜き出しで対応しようとしたので regex にしました。
コメントを追記しています。

			// "url/api" -> { "url/api", "", "" }
			// "url/base/api/register1/diagnosis2" -> { "url/base/api", "/register1", "/diagnosis2" } 
			// "url/api1/r1/d2" -> { "url/api1", "/r1", "/d2" } 
			// "url/api1/d2/r1" -> { "url/api1", "/r1", "/d2" }

2021-06-11 21:00 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +		public ushort NumberEndofSentence(string url)
Get にします。

2021-06-11 21:01 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +		private ushort[] Data()
CreateDataPreset にします。

2021-06-11 21:10 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +			var summary = new ExposureDetectionSummary(d[i++], d[i++], d[i++], new TimeSpan[d[i++]], d[i++]);
これは、ヘビーですね。ダミークラスでの対応がベストですが、今回はとりあえず、コメントだけ追加しておきます
```
			var summary = new ExposureDetectionSummary(d[index++], d[index++], d[index++], new TimeSpan[d[index++]], d[index++]);
			// ExposureDetectionSummary(daysSinceLastExposure=d[0],matchedKeyCount=d[1],maximumRiskScore=d[2],attenuationDurations=new TimeSpan[d[3]],summationRiskScore=d[4])

```

2021-06-11 21:37 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +					info.Add(new ExposureInfo(DateTime.UtcNow.AddDays(-d[i++]), TimeSpan.FromMinutes(d[i++]), d[i++], d[i++], (Xamarin.ExposureNotifications.RiskLevel)d[i++]));
> 齟齬が生まれるのではないかと思うのですが、一度確認をお願いできないでしょうか。

確認しようと思いましたが、確証が持てませんでした。ExposureInfoの第一引数は、ログでは　Exposure.Timestamp　と出ていますので、これに詳しい人を頼りたいところです。

たぶん、最初のコーディングの時からあまり深く考えられていない気がします。この変更は、下記の現状のものをより柔軟に与えられるようにしているだけです。

https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs#L61-L62

本来は、 ExposureInfo の概要として ExposureSummary がありますので、Mock の場合も、 ExposureInfo だけ与えれば、そこから　ExposureSummary 　は自動計算することが原理的には可能なはずで、最初はそうしようと思いましたが、無理でした。

あとMock としては、例えば ExposureInfoとExposureSummary の間に齟齬があるケースも、テストできる機能があった方がよいです。

2021-06-11 21:59 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +			int i = 0;
index にしました。

2021-06-15 01:51 UTC, keiji commented
@i-maruyama 
これPull Requestの向き先を`feature/debug_page`に切り換えようかと思うのですが、いかがですか？

Debugページと一体ではなく個別で取り扱うのがよいと言うことであれば、このままdevelopへ向けておきます。

2021-06-15 21:55 UTC, i-maruyama commented
> @i-maruyama
> これPull Requestの向き先を`feature/debug_page`（これから作る）に切り換えようかと思うのですが、いかがですか？

それが良いと思います。簡易ログ表示も同様にそっちにくっつけていけるとよいと思います。

そうすると、もともとの PR は develop 向けに再度復活していただくのが良いかと思います。これは先に入れておかないと、ソースコード読んで、デバッグしている人が混乱すると思います。

+ https://github.com/cocoa-mhlw/cocoa/pull/168 この StopAsync 修正はソースコードから明らかなミスなので、 develop 向けに再度復活
+ https://github.com/cocoa-mhlw/cocoa/pull/170 このPRは廃棄して、開発チームの修正である https://github.com/cocoa-mhlw/cocoa/pull/170#pullrequestreview-659729871 をdevelop 向けにPR　

二個目は私がやっても良いです。当該issue には、話の経緯を入れます。

2021-06-16 06:31 UTC, keiji commented
向き先を変えました！
GitHub Actions動くか試したいので、一回CloseしてReopenします。

2021-06-19 18:23 UTC, keiji commented
お手すきの際、レビューの反映と同じタイミングでいいので、CI（ビルド）が通るよう適宜、調整をお願いします。

2021-06-20 22:47 UTC, i-maruyama commented
対応遅くなり申し訳ありませんでした。
- https://github.com/cocoa-mhlw/cocoa/pull/191/commits/376bb93aed26c404007ed38d49702848e56d9886 は、前回最終のビルド通らないバージョン（おそらくご覧いただいた最後のバージョンで、WEB上 commit を勢いよくポチポチマージしてビルドが通らなくなっていました）
- https://github.com/cocoa-mhlw/cocoa/pull/191/commits/d40ac672e975ed9c3ce3aae541933c7bea3c96b6 は、ビルド通ると思われるバージョン（共通クラスなし)
- https://github.com/cocoa-mhlw/cocoa/pull/191/commits/376bb93aed26c404007ed38d49702848e56d9886 は、共通クラスを付けた最新

以上となっており、現状では以下のようになっております。
2 workflows awaiting approval
First-time contributors need a maintainer to approve running workflows.

2021-06-21 07:47 UTC, keiji requested changes
レビューできました。よろしくお願いします。

オープンソースプロジェクトなので、あくまでもできるときにやる。で大丈夫です。
もしお時間ない場合は言っていただければ僕側で巻き取ることもできますので、遠慮なく言ってくださいね。

2021-06-21 07:47 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +        => Regex.IsMatch(CdnUrlBase, @"^(\d+,)+\d+,*$");
style nitpick indent

```suggestion
                => Regex.IsMatch(CdnUrlBase, @"^(\d+,)+\d+,*$");
```

2021-06-21 07:47 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +        => NumberEndofSentence(CdnUrlBase);
style nitpick indent

```suggestion
            => NumberEndofSentence(CdnUrlBase);
```

2021-06-21 07:47 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +            return (new string[] { urlApi, urlRegister, urlDiagnosis });
括弧はなくても良さそう。

```suggestion
            return new string[] { urlApi, urlRegister, urlDiagnosis };
```

2021-06-21 07:47 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +        => Regex.IsMatch(GetApiUrlSegment()[0], @"^(\d+,)+\d+,?$");
style nitpick indent

```suggestion
        public ushort GetDiagnosisDataType()
            => NumberEndofSentence(GetApiUrlSegment()[2]);
        public ushort GetRegisterDataType()
            => NumberEndofSentence(GetApiUrlSegment()[1]);
        public ushort GetApiDataType()
            => NumberEndofSentence(GetApiUrlSegment()[0]);
        public bool IsDirectInputApi()
            => Regex.IsMatch(GetApiUrlSegment()[0], @"^(\d+,)+\d+,?$");
```

2021-06-21 07:47 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +                keys.Add(GenerateRandomKey(i));
ここは for 文に { } でブロックを付けてください。
（ブロックがないと気づかずに、あとから行を増やしたときに1行しか繰り返されなかったという苦い思い出があるので…）

あと、`14`がマジックナンバーになってしまっているので、定数`DAY_OF_TEK_STORED`として定義すると後から見てわかりやすいと思います。

```suggestion
            for (var i = 1; i <= DAY_OF_TEK_STORED; i++)
            {
                keys.Add(GenerateRandomKey(i));
            }
```

2021-06-21 07:47 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +            for (var i = 1; i < 14; i++)
1日前から13日前までの13日分ということでしょうか。14日分（現在のものを含めず）なので比較演算子を `<=` にしたほうがいいかなと思いました。

2021-06-21 07:47 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +            var buffer = new byte[16];
元ファイルがこうなっていることを理解した上で、ここは`buffer`として使用しているわけではないので`keyData`とした方がわかりやすいかと思います。
また、`16`については定数`KEY_DATA_LENGTH`にしておいてください。

```suggestion
            var keyData = new byte[KEY_DATA_LENGTH];
```

`TemporaryExposureKey`の引数`rollingStart`と`rollingDuration`の値域が接触確認APIの仕様に合っていない気がしますが、これについては後で僕の方でfeature/debug_pageにPR送ろうかと思います。

2021-06-25 22:36 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +            return (dataVersion);
全体にわたって VisualStudio が省略できるといっている return カッコは省略しました。

2021-06-25 23:07 UTC, i-maruyama reviewed
レビューありがとうございます。コメント反映しました。

2021-06-25 23:07 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private static readonly MockCommonUtils mockCommonUtils = new MockCommonUtils();
ここ、初期化していないのでnull が代入されていてエンバグしていました。初期化するようにしました。

2021-06-25 23:07 UTC, i-maruyama commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +        private static readonly MockCommonUtils mockCommonUtils = new MockCommonUtils();
上と同様、初期化しました。

2021-06-26 01:16 UTC, keiji reviewed
ありがとうございます。整ってきた感がありますね。
後日全体見直す予定ですが、ひとまず今回の変更分についてレビューしたのを置いておきます。

2021-06-26 01:16 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        private static readonly MockCommonUtils mockCommonUtils = new MockCommonUtils();
ありがとうございます。

ちなみに、ここはstaticでなくてもいいかなと思いました。厳密にはMockCommonUtilsは状態を持たないのでstaticでも動くけど、staticを指定する理由が思い浮かばないなぁ。みたいな所見です。

2021-06-26 01:16 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +            const int DAY_OF_TEK_STORED = 14;
定数はclass直下にまとめておいた方がいいと思います。
なにせ使ってるのがここだけなので微妙ではあるのですが…

2021-06-26 01:16 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs
> +            const int KEY_DATA_LENGTH = 16;
ここも同様ですね。定数はclass直下にまとめておいてください。

2021-07-01 17:06 UTC, keiji commented
rebased

2021-07-03 20:47 UTC, i-maruyama commented
ありがとうございます（今回いただいたコメントは全部反映しました）。

2021-07-04 16:01 UTC, keiji approved these changes
LGTM

CIの結果を見ながらfeatureブランチにマージします。
ぼくもPullRequest送るので確認いただけるとありがたいです。

2021-07-05 05:04 UTC, merged