add CI for server
cocoa-mhlw/cocoa pull request #206
Opened 2021-06-02 13:49 UTC by tatsu-jp

## Issue 番号 / Issue ID

- Close #190

## 目的 / Purpose

- サーバ側のCIを実現してコード品質を維持するため。

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[x] Other... Please describe: CI support
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```
masterブランチへpush or pull requestを作成する
(またはTriggerブランチを任意のブランチに書き換えて実行する)
```

## 確認事項 / What to check

- GitHub Actionsでビルド・テストが正常に完了することを確認

## その他 / Other information

@keiji さんに以下の3つのケースで期待通り動作することを確認していただきました（ https://github.com/cocoa-mhlw/cocoa/issues/190#issuecomment-852190156 ）。

- ビルド・テストともに正常に完了するパターン
- ビルドが通らなくなる（コードが壊れている）
- ビルドは通るがテストが通らないパターン

2021-06-03 01:53 UTC, keiji commented
ありがとうございます。
README.mdにバッジを追加するコミットも入れてしまいましょうか。

[![CI](https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml/badge.svg?branch=master)](https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml)

URLはファイル名（`CIserver.yml`）によっても変わってきます。ファイル名、ジョブ名については開発チームのレビューでお願いすることになるかもしれません。

2021-06-03 14:06 UTC, tatsu-jp commented
バッジの件、了解です。

ファイル名やジョブ名に関しては、是非レビューして頂ければと思います。プロジェクト初心者なりに理解しやすい名前にしたつもりですが、特段良いとは思っていません。サーバー開発者の理解しやすい用語や命名規則等あればそちらに合わせたいと思います。

2021-06-07 07:10 UTC, keiji approved these changes
LGTM

READMEへのバッジ追加、僕の方でコミット入れましょうか。

2021-06-07 12:56 UTC, tatsu-jp commented
@keiji さん、
URLに影響のあるファイル名等で指摘が何かしらあるかな？と待ってましたが、問題なしと言うことで良いですかね。
認識に相違なければ私の方でも作業しますが、@keiji さんの方でご対応頂いて問題ありません(むしろ助かります)。

2021-06-07 15:02 UTC, tatsu-jp commented
ブランチ変更の件を対応しました(対応しないとCIの意味がないので…)。
合わせてご確認お願いします。

2021-06-07 16:18 UTC, keiji commented on README.md
> +[![CIserver](https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml/badge.svg?branch=master)](https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml)
ブランチルールの変更に合わせて、こちらも調整お願いします！

```suggestion
[![CIserver](https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml/badge.svg?branch=develop)](https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml)
```

2021-06-08 16:06 UTC, tatsu-jp commented on README.md
> +[![CIserver](https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml/badge.svg?branch=master)](https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml)
レビューありがとうございます。
#211 を参考にして修正したのでご確認お願いします。

2021-06-10 02:16 UTC, fumiya-kume commented
[nit] LGTM (すごい)

2021-06-13 00:43 UTC, keiji requested changes
`name`だけ調整をお願いします。

2021-06-13 00:43 UTC, keiji commented on .github/workflows/CIserver.yml
> +name: CIserver
ここでやりとりがあったので、名前を`CI-Server`にしておいてもらえると。
https://github.com/cocoa-mhlw/cocoa/pull/211#issuecomment-859553572

```suggestion
name: CI-Server
```

2021-06-13 13:57 UTC, tatsu-jp commented on .github/workflows/CIserver.yml
> +name: CIserver
対応しました。

補足です。Serverの大文字小文字の間違い(コミットメッセージ側は正しい)に気づかずpushしたので、コミット履歴が2つになっています。分かりにくくなってしまいすみません…

2021-06-24 03:28 UTC, keiji approved these changes
LGTM

2021-06-24 03:35 UTC, merged