MAT関係のファイルを削除
cocoa-mhlw/cocoa pull request #209
Opened 2021-06-05 17:42 UTC by Takym

## Issue 番号

- Close #162

## 目的
- 多言語ツールキットを廃止。

## 破壊的変更をもたらしますか

```
[ ] Yes
[x] No - コードの互換性は保たれている筈です。
```

## Pull Request の種類

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone https://github.com/Takym/cocoa.git
cd cocoa
git checkout DisuseMATv2
dotnet restore
```

## 確認事項 / What to check

- [ ] 正しく言語リソースが反映される。

## その他 / Other information

- 空のリソースファイルは削除せずそのままにしてあります。
    - 空のリソースファイルを削除する場合はこのPRはマージせず、#182 をマージしてください。
- resx ファイルをUIから変更した場合、ライセンス通知は削除されてしまいます。

2021-06-07 05:28 UTC, keiji requested changes
Conflictの解消をお願いします！

2021-06-07 07:42 UTC, Takym commented
コンフリクトは解消しました。

2021-06-08 08:00 UTC, Takym commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
`Configurations` に明示的に `Debug_Mock` を指定しないと `Debug_Mock` でのビルドが不可能になってしまいます。

2021-06-08 08:06 UTC, Takym commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
`PropertyGroup` の `Label` 属性は人間が読む属性であり、MSBuild はこの属性を見ていなかったと思います。#182 ではMATの `PropertyGroup` を丸ごと削除してビルド構成に関する設定も消えてしまいました。

2021-06-08 08:45 UTC, keiji commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
何度もすみません。Debug_Mockもビルドが通ってるという認識なのですが、「使う事」というのは実行時に何らかのエラーが出ると言うことでしょうか。

https://github.com/cocoa-mhlw/cocoa/pull/182/checks?check_run_id=2594665668

2021-06-08 09:01 UTC, Takym commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
すみません。僕に少し誤解があった様です。Configurations の指定が無いと Visual Studio からはビルドできませんでした。後でもう一度調べてみます。

2021-06-08 09:08 UTC, Takym commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
推測ですが、Configurations 要素はツール類がビルド構成が存在している事を認識する為にあるのでしょう。

2021-06-08 10:50 UTC, Takym commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
下記の単純なプロジェクトファイルで検証してみました。
```csproj
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net5.0</TargetFramework>
		<Configurations>ABCD</Configurations><!-- ※ -->
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='ABCD'">
		<ABCD>xyz</ABCD>
	</PropertyGroup>
	<ItemGroup Condition="'$(ABCD)'=='xyz'">
		<None Include="a.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<ItemGroup Condition="'$(ABCD)'!='xyz'">
		<None Remove="a.txt" />
	</ItemGroup>
</Project>
```
このプロジェクトファイルは、ビルド構成 `ABCD` が指定されている場合にのみ `a.txt` を出力ディレクトリにコピーします。
`<!-- ※ -->` が付いている行の有無で Visual Studio の挙動が変わります。
* 無い場合はビルド構成 `ABCD` は認識されません。
    * しかし、コマンドラインから直接 `ABCD` を指定する事はできます。
* 有る場合は認識されます。
    * 更に上記の例では `Debug`/`Release` は認識されなくなります。

`<Configurations>Debug;Release;Debug_Mock</Configurations>` を指定しておく事により Visual Studio に `Debug_Mock` を認識して貰う事ができます。指定しなければUIからは選択する事ができなくなります。

2021-06-08 10:51 UTC, Takym commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
> `Configurations` に明示的に `Debug_Mock` を指定しないと `Debug_Mock` でのビルドが不可能になってしまいます。
これはただの勘違いで、正しくは「Visual Studio でのビルドが不可能になってしまいます。」と書くべきでした。

2021-06-08 17:14 UTC, b-wind commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
> 正しくは「Visual Studio でのビルドが不可能になってしまいます。」

MAT 自体には直接関わりが無さそうなので別 Issue/PR で対応した方が取り込む方も管理しやすいかなと思いました。

2021-06-09 07:59 UTC, cocoa-dev approved these changes

2021-06-09 07:59 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <Configurations>Debug;Release;Debug_Mock</Configurations>
ありがとうございます。
Visual Studio でのビルドができない現象ですが、Mac だと問題なく動き、Windows 環境でのみ再現することが確認できました。
こちらの修正で問題ないと思います。

2021-06-09 08:03 UTC, keiji approved these changes
👍️

2021-06-09 08:06 UTC, merged

2021-06-09 08:10 UTC, Takym commented
マージして頂きありがとうございます。

2021-06-09 08:13 UTC, keiji commented
こちらこそ、いつもありがとうございます。
MATがなくなって見通しが良くなりましたね😊

2021-06-09 08:17 UTC, Takym commented
今、MAT に関する `Import`、`Target` の消し忘れを見つけましたので、PRを作成します。