ログ出力に関する変更
cocoa-mhlw/cocoa pull request #226
Opened 2021-06-11 04:08 UTC by Takym

## Issue 番号
- Close #148
- Close #225

## 目的

## 破壊的変更をもたらしますか
```
[ ] Yes
[ ] No
```

## Pull Request の種類
```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```

```

## 確認事項 / What to check

-

## その他 / Other information

2021-06-13 22:24 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
>      public class FFImageLoadingLogger : IMiniLogger
このクラスって今使われていますか？
もし使われていなければ手を付けずに不要なクラスとして削除した方がいいかもしれません。

2021-06-13 22:24 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/Logs/LogUploadService.cs
>  }
👍

2021-06-13 23:56 UTC, Takym commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
>      public class FFImageLoadingLogger : IMiniLogger
このクラスは使われていないという指摘はありましたね。`DebugLogger` と同じインターフェースを持っており違いもよく分かりません。廃統合して `Logger` 名前空間に移転するのが良いのかもしれません。

2021-06-14 00:37 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
>      public class FFImageLoadingLogger : IMiniLogger
このPull Requestでは掲題の「ログ出力」に関するものに限定して、統廃合や移転や削除については別の機会にしましょう。
ひとまず、変更を戻して、ここはレビューをしなくても良いようにするのが良いと思います。

2021-06-14 03:42 UTC, Takym commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
>      public class FFImageLoadingLogger : IMiniLogger
打消しを行うコミットを（手動で）作成しました。https://github.com/cocoa-mhlw/cocoa/pull/226/commits/18165088e4fa98dc42fa9f0397cc6a82b49c25a9

2021-06-14 03:44 UTC, keiji requested changes
よろしくお願いします

2021-06-14 03:44 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
> +using Prism.Logging;
このファイルについてはdiffが出ないようにしておいて欲しいので、このあたりも打ち消しお願いします！

2021-06-14 03:44 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
> +        private readonly ILogger _logger;
ここも、消したら一緒なので戻しておいてください

2021-06-14 03:51 UTC, Takym commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
> +using Prism.Logging;
すみません。手動で書き換えたので見落としていました。

2021-06-14 03:54 UTC, Takym commented
差分を無くすためにBOMを追加しましたが、不要でしたら取り消します。

2021-06-14 09:39 UTC, b-wind commented
FFImageLoadingLogger.cs 自体は、 #115 で削除対象に含まれているようですね。

2021-06-14 11:44 UTC, Takym commented
#115 に既に含まれているのであれば #225 で話していた Issue は建てる必要は無さそうですね。

@keiji さん
https://github.com/cocoa-mhlw/cocoa/issues/225#issuecomment-860162179 で話されていた Android 側での `DebugLogger` の設定は行った方が良いでしょうか？

2021-06-14 12:28 UTC, Takym reviewed
`DebugLogger` を改善しました。ご確認お願い致します。

2021-06-14 12:28 UTC, Takym commented on Covid19Radar/Covid19Radar/Services/DebugLogger.cs
> +        }
最初はコンストラクタから `ILoggerService` を受け取っていましたが、ビルドエラーが発生したため `DependencyService.Resolve<T>()` を使ってサービスを取得する様に変更しました。しかし、初期化前のタイミングでは `DependencyService.Resolve<T>()` は `null` を返していましたので、最初のログ出力時に取得する様に変更しました。

2021-06-23 07:22 UTC, Takym commented
#225 でも書きましたが、`DebugLogger`/`FFImageLoadingLogger` を削除し、ログ出力先を `Debug.WriteLine` から `LoggerService.Debug` へ修正しました。

2021-06-23 08:29 UTC, keiji commented
ブランチの向き先変更しました。
CIを動かすために一度Closeとreopenします。

2021-06-23 08:36 UTC, Takym commented
ありがとうございます。

2021-06-23 08:36 UTC, Takym commented
CI が一部失敗している様ですので後程確認します。

2021-06-23 09:39 UTC, Takym commented
修正しました。`DebugLogger` への削除を忘れていたのが原因でした。

2021-07-13 00:33 UTC, keiji approved these changes
LGTM

2021-09-08 12:07 UTC, merged