Prism.Plugin.Logging.AppCenter への依存を削除
cocoa-mhlw/cocoa pull request #239
Opened 2021-06-14 14:34 UTC by Aqua-ix

## Issue 番号 / Issue ID

- Close #238 

## 目的 / Purpose

- 現在使用されていない `Prism.Plugin.Logging.AppCenter` への依存関係を削除します。
- 46cb280 で削除されるべき所の対応が漏れていたものと考えられます。

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Pull Request の種類 / Pull Request type

```
[ x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```

```

## 確認事項 / What to check

-

## その他 / Other information

2021-06-14 18:51 UTC, b-wind reviewed
お手数ですが、指摘した３点は別のIssueで扱っておりここで変更してしまうとコンフリクトします。
変更を戻して貰うようお願い致します。

2021-06-14 18:51 UTC, b-wind commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            global::FFImageLoading.ImageService.Instance.Initialize(new FFImageLoading.Config.Configuration());
ここは今回の Issue に関係無いと思うので、変更しないようお願い致します。

2021-06-14 18:51 UTC, b-wind commented on Covid19Radar/Covid19Radar/Services/DebugLogger.cs
> -﻿/* This Source Code Form is subject to the terms of the Mozilla Public
このファイルは別 Issue で扱っているので削除しない様お願い致します。

2021-06-14 18:51 UTC, b-wind commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
> -﻿/* This Source Code Form is subject to the terms of the Mozilla Public
このファイルは別の Issue で扱っているので変更しないようお願い致します。

2021-06-14 21:32 UTC, keiji requested changes
ありがとうございます。とても助かります。

依存関係以外の部分の変更が含まれてしまっているので、その部分の変更は取り除いてもらえるとうれしいです！

2021-06-14 21:32 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
> -    </PackageReference>
:+1:

2021-06-15 00:31 UTC, Aqua-ix commented
@b-wind @keiji 
レビューありがとうございます。てっきり依存関係のある箇所をまとめて修正すべきであると勘違いしておりました...
ご指摘いただいた箇所については 79407a0 にて差し戻しました。

2021-06-15 01:18 UTC, b-wind commented
あれ、コードの参照になってないです？

2021-06-15 01:21 UTC, keiji commented on CONTRIBUTORS.md
> +- Soichi Ikebe (Xamarin / Documentation)
COVID-19Radarの頃からコントリビュートしていただいていたのですね。
お力添えいただき光栄です。

2021-06-15 01:21 UTC, keiji commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.1114" />
確認なのですが、ここを消すと`DebugLogger`と`FFImageLoadingLogger`のビルドが通らなくなるとか、そういう理由で２つのクラスを消したのでしょうか。

そうであればこのコミットで消してしまいましょうか。ビルドが通るかどうかはCIでチェックします。

2021-06-15 01:24 UTC, Aqua-ix commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.1114" />
その辺りのご説明が不足しており申し訳ありません。
FFImageLoadingLogger については以下でコメントしたとおりビルドエラーが発生したため削除しました。
https://github.com/cocoa-mhlw/cocoa/pull/239#commitcomment-52160487
DebugLogger については、特にビルドエラーにはならなかったのですが、#58 で指摘されていた箇所であったため削除の判断に至りました。

2021-06-15 01:27 UTC, b-wind commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.1114" />
using Prism.Logging; が困る原因っぽいですね。この行を単に消してどうなるかはよく分かりません。

2021-06-15 01:36 UTC, keiji commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.1114" />
2つのファイルを削除してしまいましょう。
`FFImageLoadingLogger.cs`については #115 でも消していますが、後から調整すればいいだけなので他のPull Reqeustとの衝突は気にしないでください。

ちなみに、

https://github.com/cocoa-mhlw/cocoa/pull/239/files/87ea2cbd36c53c3d3f1641b270cb9f01e846692f#diff-41dab84b2325b883223c81abfe57cf9987780cba889c7e72032d2f9dd043427eL48-R48

ここについても目的のために必要な変更だったりしますか？

2021-06-15 01:37 UTC, Aqua-ix commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.1114" />
`ILogger` がAppCenterに依存していそうな箇所は見つけられなかったので、AppCenterパッケージを除くとエラーになるのは少し不思議ですね。

2021-06-15 01:46 UTC, Aqua-ix commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.1114" />
> 2つのファイルを削除してしまいましょう。
> `FFImageLoadingLogger.cs`については #115 でも消していますが、後から調整すればいいだけなので他のPull Reqeustとの衝突は気にしないでください。
> 
承知しました。この後修正します。

> https://github.com/cocoa-mhlw/cocoa/pull/239/files/87ea2cbd36c53c3d3f1641b270cb9f01e846692f#diff-41dab84b2325b883223c81abfe57cf9987780cba889c7e72032d2f9dd043427eL48-R48
> 
> ここについても目的のために必要な変更だったりしますか？

Loggerを生成する際に DebugLogger を参照しているため、DebugLoggerを消すのであれば必然的にこちらの変更が必要になってきます。
また、今回の対応が 46cb280 の対応漏れをカバーするものであるという観点で見たときに、Android側では既にこの対応がなされていたためiOS側もそれに倣うべきなのではないかという考えです。
https://github.com/cocoa-mhlw/cocoa/blob/46cb280c17ca15a65332ca366017a4dd48e3d359/Covid19Radar/Covid19Radar.Android/MainActivity.cs#L40

2021-06-15 01:48 UTC, keiji commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.1114" />
ありがとうございます。
「よく見たら`DebugLogger`あるな」って、質問してから気づきました。

よろしくお願いします。

2021-06-15 03:51 UTC, Aqua-ix commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Prism.Plugin.Logging.AppCenter" Version="7.2.0.1114" />
以下のコミットで修正しました。
9ae9d24

2021-06-15 04:32 UTC, b-wind commented
LGFM!

2021-06-15 14:16 UTC, keiji approved these changes
CIの結果です。
https://github.com/keiji/cocoa/actions/runs/938538409

2021-06-15 15:41 UTC, Aqua-ix commented
CIによる検証ありがとうございます。
こちら見る限り問題なさそうですね。

2021-06-22 01:43 UTC, Takym commented on Covid19Radar/Covid19Radar/Services/DebugLogger.cs
> -﻿/* This Source Code Form is subject to the terms of the Mozilla Public
このファイルは削除して頂いて構いません。

2021-06-22 01:44 UTC, Takym commented on Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs
> -﻿/* This Source Code Form is subject to the terms of the Mozilla Public
このファイルは削除して頂いて構いません。

2021-07-19 05:54 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            global::FFImageLoading.ImageService.Instance.Initialize(new FFImageLoading.Config.Configuration());
すでに Resolved になっていますが、誰も返信していないので、他の人が見てもわかるよう記載します。

https://github.com/cocoa-mhlw/cocoa/commit/46cb280c17ca15a65332ca366017a4dd48e3d359 のコミットを見る限り、今回の Issue に関係ありそうなので削除して問題ないと思います。

2021-07-19 06:09 UTC, cocoa-dev approved these changes

2021-07-19 06:16 UTC, cocoa-dev commented
@Aqua-ix 
PR ありがとうございます。 LGTM です :)
ただコンフリクトが発生しているので、お手数ですが解消をお願いします。

2021-07-19 07:08 UTC, Aqua-ix commented
@cocoa-dev 
ご確認ありがとうございます。
developにリベースし、コンフリクトを解消しました。

2021-07-19 08:07 UTC, merged

2021-07-19 08:08 UTC, cocoa-dev commented
@Aqua-ix 
迅速なご対応ありがとうございます。
マージしました。