Feature/add cdocuments
cocoa-mhlw/cocoa pull request #24
Opened 2021-02-26 11:53 UTC by halsk

## Purpose

* `README` に、コントリビューションを歓迎するかたちに変更
* `CONTRIBUTING.md` として、コントリビューションに関するガイドラインを追加
* `OPERATION_POLICY.md` として、GitHub の運用方針を追加

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Not needed

## What to Check
* ドキュメントをご確認ください。

## Other Information

2021-02-26 13:51 UTC, ktgw0316 requested changes

2021-02-26 13:51 UTC, ktgw0316 commented on OPERATION_POLICY.md
> +（３）日本国政府のITシステムに関する問い合わせや
文が途中で途切れているように思えます。

2021-02-26 13:51 UTC, ktgw0316 commented on OPERATION_POLICY.md
> +（１）当リポジトリのソースコードについては、[ライセンス条項](LICENSE.txt)によって提供されています。
細かいですが、1項目だけなので箇条書きでなくて良いと思います。

2021-02-26 13:51 UTC, ktgw0316 commented on OPERATION_POLICY.md
> +（１）日本国政府のITシステムに関する仕様や技術ドキュメントに関わる情報
細かいことで申し訳ないですが、[markdownの連番付き箇条書き](https://gist.github.com/LambdaNote/0d33b7d8284a3c99cffd1a5aa83c115f#%E7%AE%87%E6%9D%A1%E6%9B%B8%E3%81%8D)を使いませんか？（下記「３ 注意事項」も）

2021-03-01 05:41 UTC, halsk commented on OPERATION_POLICY.md
> +（３）日本国政府のITシステムに関する問い合わせや
ご指摘ありがとうございます。修正しました。

2021-03-01 05:42 UTC, halsk commented on OPERATION_POLICY.md
> +（１）当リポジトリのソースコードについては、[ライセンス条項](LICENSE.txt)によって提供されています。
対応しました。

2021-03-01 05:42 UTC, halsk commented on OPERATION_POLICY.md
> +（１）日本国政府のITシステムに関する仕様や技術ドキュメントに関わる情報
対応しました

2021-03-02 03:27 UTC, merged