接触判定時にローカル通知を表示する
cocoa-mhlw/cocoa pull request #299
Opened 2021-07-29 23:43 UTC by keiji

## Issue 番号 / Issue ID

- Close #207
- Close #290
 
## 目的 / Purpose

接触確認API（ExposureNotification）のExposureWindow mode（iOSではENv2）対応に向けて、ローカル通知を実装する。

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

## 確認事項 / What to check

### Android
 - COCOAの初期設定後、ホーム画面が表示されると通知チャンネルが作成される
 - 接触判定時にローカル通知が表示される

### iOS
 - COCOAの初期設定後、ホーム画面が表示されるタイミングで通知の許諾ダイアログが表示される
 - アプリがバックグラウンドにあるとき、接触判定が行われるとローカル通知が表示される
 - アプリがフォアグラウンドにあるとき、接触判定が行われるとローカル通知が表示される（iOSではフォアグラウンド通知には手当が必要）
 - iOS14未満でローカル通知が表示される
 - iOS14以上でローカル通知が表示される（バージョンによるAPIの違い有）

## その他 / Other information

2021-07-30 00:22 UTC, keiji reviewed
中国語の翻訳が欲しいな…

2021-07-30 00:22 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
> +    </PackageReference>
`NotificationCompat`を使うため、`AndroidX.Core`に移行。
移行に伴い`Android.Support`系のライブラリを削除した。

2021-07-30 00:22 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> + * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
ライセンス通知ﾖｼｯ

2021-07-30 00:22 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> + * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
ライセンス通知ﾖｼｯ

2021-07-30 00:22 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/ILocalNotificationService.cs
> + * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
ライセンス通知ﾖｼｯ

2021-07-30 00:22 UTC, keiji commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +      <Generator>PublicResXFileCodeGenerator</Generator>
Platform ProjectからAppResourcesの文字列を参照するため、PublicResXFileCodeGeneratorに変更。

2021-07-30 01:09 UTC, keiji commented
#221 がマージされたのでライセンス情報を更新します。

2021-07-30 06:27 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
iOSの慣習としてメッセージングの定数値にBundleIDをprefixとしてつけていますが、
Bundle IDはコード内に入れないポリシーという話も聞いたのでご確認お願いします

2021-07-30 06:28 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> -        //}
Notificationのバッジ周りの処理がコメントアウトとして記載されていたのでついでに削除しました

2021-08-02 07:56 UTC, cocoa-dev commented
@keiji @kazuhiro4949 
可能でしたら、PR の概要などにローカル通知のスクリーンショットを貼っていただけると、イメージがつきやすいので嬉しいです。

2021-08-02 07:56 UTC, keiji commented
やります。

2021-08-02 08:37 UTC, keiji commented
@cocoa-dev ローカル通知のスクリーンショットです。

## Android

<img width="744" alt="Screen Shot 2021-08-02 at 17 18 30" src="https://user-images.githubusercontent.com/932136/127830401-75dd56b7-24c9-44d3-b1fd-b3ae5b702640.png">

## iOS

![Screen Shot 2021-08-02 at 17 35 09](https://user-images.githubusercontent.com/932136/127830420-e84d3ada-9065-4839-84b5-c8a971e4c24b.png)

2021-08-02 09:01 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Resources/drawable/ic_notification.xml
> +<!-- Copyright (C) Ministry of Health, Labour and Welfare, All Rights reserved. -->
シンボルマークについてはCOCOAでアイコンとしてすでに使用されているものです。 厚生労働省のシンボルマークについてはMPL 2.0の対象外であることから、コピーライトを All rights reserved としています（ 参考: #3 ）。

2021-08-02 09:05 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
この点、事前の検討でも話題に上ったのですが将来的に Bundle ID が変わるという事態が想定しづらく、このままでいきましょう。

Xamarin.Essentialsとかで簡単にBundle IDを取得できるよ。みたいな知見があれば提案いただけるとうれしいです。

2021-08-02 10:01 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Resources/drawable/ic_notification.xml
> +<!-- Copyright (C) Ministry of Health, Labour and Welfare, All Rights reserved. -->
すみません、質問の意図としては「通知アイコンはCOCOAのアプリアイコンと同じデザインで同意が取れているか」でした。

参考リンクのご共有ありがとうございます。
一応確認ですが、アイコンをモノクロにするのも問題ないでしょうか？

2021-08-02 10:12 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
事前の検討で問題ないと判断されたのでしたら、このままで問題ありません。

Bundle ID は `var bundleID = NSBundle.MainBundle.BundleIdentifier;` でかんたんに取得できそうです。

2021-08-03 00:29 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
コメントありがとうございますmm 
必ずしもBundleIDに対して厳密である必要は特になく、使っているライブラリを含め一意の値である必要があるためアプリ内で使用している文字列はプレフィックスに今のアプリのBundleIDをつけてるという意図になります。
ちょっと紛らわしいかもしれないのでAndroidと値は合わせる修正入れますね。
どちらかというと定数値であることが大事なので、ランタイムで生成するのではなく埋め込んでおきたいです。

2021-08-03 00:53 UTC, cocoa-dev requested changes

2021-08-03 00:53 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> -        //}
不要なコメントアウトの削除ありがとうございます。
こちら問題ないので解決とします。

2021-08-03 00:53 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +      <Generator>PublicResXFileCodeGenerator</Generator>
Android で言語に応じた通知チャネル名を取得するためだけに、文字列リソース全体を public にするのに多少抵抗がありますが、問題ありません。
プラットフォームごとのプロジェクトで文字列リソースを管理する方法も考えられますが、一元管理するほうがベターでしょうか。

2021-08-03 00:53 UTC, cocoa-dev commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +## Xamarin.Android bindings for AndroidX - core
ライセンスを更新する場合、元にしたページの URL を共有していただきたいです。

2021-08-03 02:01 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +      <Generator>PublicResXFileCodeGenerator</Generator>
@keiji 
すみません、Android だとアプリ名をローカライズするために、すでに「Resources > values-* > Strings.xml」が存在しますね。
そしたら各 `Strings.xml` に通知チャネル名を記述し、全体の文字列リソースは Internal のままとするのがベストだと思います。

2021-08-03 02:06 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
想像したより簡単ですね。

@kazuhiro4949 どうでしょう。JSONファイルを読み込んで差し込みとなると大変ですが、この方法であれば手間はかからないように思います（定数化は解除しなければならなさそうですが）。

2021-08-03 02:12 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Resources/drawable/ic_notification.xml
> +<!-- Copyright (C) Ministry of Health, Labour and Welfare, All Rights reserved. -->
通知アイコンをアプリアイコンと同じデザインとして提案することは自然な流れと考えていますが、政府との調整等、必要な手続きや調整については開発チームの皆さんにお任せします。よろしくお願いします。

なお、一般アプリで通知アイコンがモノクロで表示されるのはAndroid 5.0での標準的な動作です。単色を指定することはできますが、シンボルマークのような2色構成は仕様として表示できないという認識です。

https://stackoverflow.com/questions/45874742/android-color-notification-icon

2021-08-03 02:14 UTC, keiji commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +## Xamarin.Android bindings for AndroidX - core
https://www.nuget.org/packages/Xamarin.AndroidX.Core/

2021-08-03 02:14 UTC, keiji commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +## Xamarin.Android bindings for AndroidX - recyclerview
https://www.nuget.org/packages/Xamarin.AndroidX.RecyclerView/1.0.0-preview03

2021-08-03 02:23 UTC, keiji commented
@cocoa-dev Android版の通知、本文が「接触した可…」で切れてしまっていることに気づいたので調整します。

2021-08-03 02:26 UTC, keiji commented
<img width="785" alt="Screen Shot 2021-08-03 at 11 26 04" src="https://user-images.githubusercontent.com/932136/127947927-110de657-5236-4de6-b1e3-1a2150aaafa5.png">

Android版の通知、全文を展開して利用者が読めるようにしました。

2021-08-03 02:30 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Resources/drawable/ic_notification.xml
> +<!-- Copyright (C) Ministry of Health, Labour and Welfare, All Rights reserved. -->
開発チーム内で確認し、通知アイコンのデザインについて問題ありませんでしたので Resolved とします。

2021-08-03 02:41 UTC, keiji commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +      <Generator>PublicResXFileCodeGenerator</Generator>
@cocoa-dev 
`res/values/strings.xml`に置くのは、言語リソースの管理が分散することになり、ベストとは言えないと考えます。
現在は通知チャンネル名だけですが、今後、iOSの方でも通知の許諾が得られていない場合に利用者に設定方法を案内するダイアログ表示などをする必要も想定されます。

大前提として、Xamarin.Formsを使う限り言語リソースはアプリ名など特殊な事例を除いてはXamarin.Formsの仕組みであるAppResourcesで一元的に管理するのが妥当と考えます。

また AppResourcesのpublic化は、https://github.com/cocoa-mhlw/cocoa/issues/269#issuecomment-873412437 のような、実行環境の言語設定でUI関係のテストが失敗する課題をもっともスマートに解決する方法の一つでもあります。

2021-08-03 03:10 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +        private const int NOTIFICATION_ID_EXPOSURE = 0x1234;
[質問]
`0x1234` はどのような意味があるでしょうか？

2021-08-03 03:13 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_CHANNEL_ID = "notification_channel_cocoa_202107";
バナーというのはヘッドアップ（他のアプリを使っているときに上から降りてくる通知）のことでしょうか。

ヘッドアップはしませんが、通知一覧には表示されます。

2021-08-03 03:15 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Builder(NOTIFICATION_CHANNEL_ID, NotificationManagerCompat.ImportanceDefault)
バナーというのはヘッドアップ（他のアプリを使っているときに上から降りてくる通知）のことでしょうか。

ヘッドアップはしませんが、通知一覧には表示されます。

2021-08-03 03:17 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Builder(NOTIFICATION_CHANNEL_ID, NotificationManagerCompat.ImportanceDefault)
すみません、「バナー」は iOS の用語でした。「ヘッドアップ」のことです。
ヘッドアップしないのは仕様として問題ないでしょうか？

2021-08-03 03:17 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_CHANNEL_ID = "notification_channel_cocoa_202107";
通知チャンネルも設定の更新時に既存のチャンネルのremoveが必要になります。`exposure_notification`にしてしまうと、設定変更時に次のCHANNEL_IDを付けるときに悩むことになるので、バージョンや日付等に依存した形式にした方が良いと考えます。
本来はバージョン名を負荷するのが良いのですが、現時点で次のバージョン名は不定なので、日付を採用しています。

2021-08-03 03:19 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Build();
DescriptionはXamarinでも設定できます。
その上で、現状COCOAのNotificationChannelは1つだけで、アプリの特性上通知の用途も明確なので設定していません。

2021-08-03 03:20 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_CHANNEL_ID = "notification_channel_cocoa_202107";
Android の通知チャネルについては勉強不足でした。
ではこのままで問題ありません。

2021-08-03 03:21 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +        private const int NOTIFICATION_ID_EXPOSURE = 0x1234;
NOTIFICATION_IDなので数字に意味はありません。
アプリの通知で一意であれば0x999であっても、0x0であっても問題ないという認識です。

2021-08-03 03:21 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Build();
あえてセットしていないという理由がわかったので問題ありません。
解決とします。

2021-08-03 03:23 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
これはVisual Studio for macのコードアシストでSuppress Issuesを選択すると、最初と最後にコメントを付ける仕様になっています。ここで変更すると今後、同様の処理で人に手で作業が必要になるので、このままいきましょう。

2021-08-03 03:26 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +        private const int NOTIFICATION_ID_EXPOSURE = 0x1234;
承知しました。問題ありませんので解決とします。

2021-08-03 03:26 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
知りませんでした。自動生成ならこのままで問題ありません。

2021-08-03 03:27 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                0x0,
Activityに与えるRequestCodeなので値そのものに意味はありません。
マジックナンバー化して、呼び出し元が異なることを示すために値を`0x01`に変更しました。REQUEST_CODEが増えるようであればMainActivityにpublic staticで持たせても良いかもしれませんね。

2021-08-03 03:34 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                0x0,
修正ありがとうございます。
https://github.com/cocoa-mhlw/cocoa/pull/299/commits/c074771cf8f41a9780078c1607985be476b3b66c のコミットを確認しました。
今のところは private で定数化するのみでも問題ないと思うので、解決とします。

2021-08-03 03:42 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Builder(NOTIFICATION_CHANNEL_ID, NotificationManagerCompat.ImportanceDefault)
自分が利用者だったら、ヘッドアップはして欲しくないと考えています。別のアプリを開いていて、他の人が画面をのぞき見できる状態で「重要なお知らせ」と出てくるのは避けたいので。

政府との調整等、仕様確定にあたり必要な手続きや調整については開発チームの皆さんにお任せします。よろしくお願いします。

2021-08-03 05:48 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Build();
COCOAの対象OSはAndroid 6以上なのですが、`SetPriority`は必要ないでしょうか？
Defalutだから設定必要なく省いているのでしたらすいません。。

2021-08-03 05:48 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
> +            if (exposureInformationList.Count > 0)
この条件で通知を呼ぶと、過去に陽性者との接触があった端末では、接触確認が行われるたびにローカル通知が表示されてしまいます。
ENが表示する通知と同じタイミング、具体的には`userExposureSummary.HighestRiskScore >= config.MinimumRiskScore`の条件の中で呼ぶのが適切ではないかと思います。

2021-08-03 05:57 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Build();
NotificationCompat.BuiderではPriorityを指定しない場合はPriority.Defaultになります。

https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/core/core/src/main/java/androidx/core/app/NotificationCompat.java?#1078

2021-08-03 06:03 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
> +            if (exposureInformationList.Count > 0)
おお、助かりました。
すぐに直します！

ローカル通知自体はデータ保存の後、最後の最後にやりたいと考えているので、接触が検出できたかどうかをフラグで管理しようと思います。

2021-08-03 06:08 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
>              exposureNotificationService.SetExposureInformation(userExposureSummary, exposureInformationList);
これ、`if (isExposureDetected)` の中に入れてしまっても良いかもしれない。

2021-08-03 06:20 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
>              exposureNotificationService.SetExposureInformation(userExposureSummary, exposureInformationList);
やりました。

2021-08-03 07:59 UTC, cocoa-dev commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +## Xamarin.Android bindings for AndroidX - recyclerview
[質問]
`recyclerview` は使っていないように見えるのですが、ローカル通知で内部的に使っているのでしょうか？

2021-08-03 08:01 UTC, keiji commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +## Xamarin.Android bindings for AndroidX - recyclerview
これRecyclerVIewのNuGetパッケージをリンクしておかないとビルドできない現象が手元で起きています。AndroidX.Coreと何か関係がある可能性があります。

コードとして使っていませんが、明示的にリンクしているのでライセンスに含めています。

2021-08-03 08:03 UTC, cocoa-dev commented on COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
> +## Xamarin.Android bindings for AndroidX - recyclerview
承知しました。少し気になりますが、理由がわかったので解決とします。

2021-08-03 08:53 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Build();
ありがとうございます。承知しました。

2021-08-03 08:56 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs
> +            if (exposureInformationList.Count > 0)
修正ありがとうございます！
問題ないので解決とします。

2021-08-03 14:06 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
@keiji @cocoa-dev そうですねぇ、ちゃんとアプリのBundleIDに合わせないとまずいといったことではなく、あまりそこまでしっかりとやりたいものでもないので、紛らわしたを解消することを優先してAndroidと同じ文字列にしようと思います。

2021-08-03 14:22 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
Androidとの共通化は必要ないと思います。特にiOSの方はあとからキャンセルして再登録のようなものがないと言う認識なので。

`[Bundle ID] + 文字列` の `[Bundle ID]`の部分を`NSBundle.MainBundle.BundleIdentifier`で取得する方法でどうでしょうかという意味でした。

2021-08-03 14:33 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
@keiji それでも大丈夫なのですが、ほぼただの慣習でBundleIDを使う必要性は殆どないのでBundleIDを抽象化するために変数から取るのはやりたいことに対してオーバースペックかなと思いまして。
文字列そのものというより、生文字列のルールをAndroidと合わせて↓とかでいいかなと思っております。
```
NOTIFICATION_ID = "notification_id_cocoa_202107"
```

> あとからキャンセルして再登録のようなものがない

あー登録済みの通知のキャンセルなどは可能ではありますね。通知を受け取った後のハンドリングはそのIDを使うことになります。(通知の削除や画面遷移など)

2021-08-03 14:39 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
だとすると、

```
NOTIFICATION_ID = "notification_id_cocoa"
```

が、良いと思います。

Androidで `_202107` がついているのは通知チャンネルのIDで、通知そのもののIDとは別ものなのです。通知チャンネルはシステムに登録するときのIDで、通知チャンネルの設定を変えるときには上書きできないので、一度削除してから再登録することになります。

今後、通知チャンネルの更新（設定変更）が重なれば、これまで存在した古い通知チャンネルIDを全部消して、最新の通知チャンネルを登録するという流れになることが想定されます。 `_202107` のような値を入れているのはそのためです。

iOSの場合は、そういった管理が必要なさそうなのでsuffixは付けずに `notification_id_cocoa` とするのが良いと思います。

2021-08-03 14:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
@keiji なるほどです。```notification_id_cocoa``` が良さそうだと思ったのでそれにしようと思いますmm

2021-08-03 14:57 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
修正しました。https://github.com/cocoa-mhlw/cocoa/pull/299/commits/aca7af21d8f7a17a2c11ad7df9bd0e8a75ff9ae7

2021-08-04 01:11 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.iOS/Services/LocalNotificationService.cs
> +        private const string NOTIFICATION_ID = "jp.go.mhlw.covid19radar.LocalNotificationService.NotificationId";
修正ありがとうございます。問題ないと思うので解決とします。

2021-08-04 01:20 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            completionHandler(UNNotificationPresentationOptions.Banner | UNNotificationPresentationOptions.List);
現状、Android と iOS で通知の表示場所が異なります。
（Android はヘッドアップしないが、iOS はバナー表示する）

こちら仕様検討中で、確定したら再度コメントします。

2021-08-04 02:45 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.Android/Services/LocalNotificationService.cs
> +                .Builder(NOTIFICATION_CHANNEL_ID, NotificationManagerCompat.ImportanceDefault)
ヘッドアップはしないことに決まりました。
実装を変える必要がないので解決とします。

2021-08-04 04:05 UTC, cocoa-dev commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            completionHandler(UNNotificationPresentationOptions.Banner | UNNotificationPresentationOptions.List);
iOS はバナー・ロック画面・通知センターのすべてに通知が来てもいいと決まりました。
実装を変える必要がないので解決とします。

2021-08-04 04:08 UTC, cocoa-dev approved these changes
実装ありがとうございました。Approve します。

ひとつだけ、通知のチャネル名（Android のみ）・タイトル・テキストは調整中で、内部で修正する可能性があります。
また、中国語の文言は未実装なので、こちらは確実に内部で追加します。

2021-08-04 04:30 UTC, merged