Add Routing from local push for ios
cocoa-mhlw/cocoa pull request #324
Opened 2021-08-14 10:17 UTC by kazuhiro4949

## Issue 番号 / Issue ID

- Close #321
- 
## 目的 / Purpose

- ローカル通知からの接触確認ページへの遷移を実装。
- iOSのケースのみを考慮した実装をとりあえずやっている

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```

```

## 確認事項 / What to check
- 画面遷移の具体的な実装はApp or ViewModel内で吸収してiOS・Androidのライフサイクルから切り離したいが可能か? 
- Routing自体をどこで行うべきか？
- 起動時の処理を変えざるおえなさそうなのでAppの処理の流れをちょっと変えたい

## その他 / Other information

2021-08-14 10:36 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +                ((App)App.Current).NavigateToSplash();
起動導線によって画面表示の方法を変えられるよう、Appの初期化Splash画面への遷移を切り離し、ライフサイクル上の呼び出すタイミングを変更しています。Androidの方の実装も同様に切り離しているのでここはその方針で良さそう？

2021-08-14 10:36 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +    }
遷移先をenumで定義して、各PFからはこの値を渡すようにしてみました

2021-08-14 10:36 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +        ((App)App.Current).setDestination(DeepLinkDestination.ContactPage);
とりあえず今は通知を受け取ったら必ずContactPageをセット

2021-08-14 10:36 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs
> +                    var destination = parameters.GetValue<DeepLinkDestination?>("destination");
起動時にタイミングを確実に制御できるようView階層の仕組みに乗っかって遷移先を引き回すようにしています

2021-08-14 13:12 UTC, kazuhiro4949 commented
ルーティングに関する共通FW側で行う仕事・提供するIFをAndroidも踏まえて検討した

2021-08-18 13:42 UTC, keiji requested changes
プロジェクトをiOSで実行すると起動直後に落ちました。

おそらくAppDelegateのAppクラスのインスタンス化をAppDelegateの初期化と同時に行っているためと思われます（詳細コメントしました）。

また、Appを表示した後、画面遷移のコードがないためか起動直後の初期画面で止まってしまう現象も起きています（App.InitializeでNavigateToSplashを実行すると期待通りに動くようになりました）。

確認、よろしくお願いします！

2021-08-18 13:42 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs
>                  else
`HomePage`が与えられたときの処理も追加することで、`App. destination`をnullableからnonnullとして取り扱うことができそうです。

2021-08-18 13:42 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            notificationCenterDelegate.OnRecieved += (UserNotificationCenterDelegate sender, UNNotificationResponse response) => {
フォーマッターを適用して `{}`はそれぞれ独立した行になるようにしてください。

2021-08-18 13:42 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            };
ここは消しても動くような気がするのですが、`FinishedLaunching`は通らず`OnActivated`が呼ばれる経路があったりしますか？

2021-08-18 13:42 UTC, keiji commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +        ContactPage
ContactPageだとお問い合わせページと間違える可能性があるので、ページ名に合わせて `ContactedNotifyPage` とするのはどうでしょうか。

2021-08-18 13:42 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            UNUserNotificationCenter.Current.Delegate = notificationCenterDelegate;
タップしたときの挙動なので`this.xamarinApp.NavigateTo(DeepLinkDestination.ContactPage);`に変えた上で`OnActivated`の方の同じ処理は消しても良いかなと思いました。

2021-08-18 13:42 UTC, keiji commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +                    _ = await NavigationService.NavigateAsync("/" + nameof(MenuPage) + "/" + nameof(NavigationPage) + "/" + nameof(HomePage) + "/" + nameof(ContactedNotifyPage));
ここはSplashPageにParamsを付けて呼ぶようにした方がシンプルだと思います（ユーザーは通知をタップすると必ずスプラッシュページを見ることになりますが）。

ここで直接`ContactPage`を呼んでしまうと、（上で`NavigateToSplash`を実行するようにしたせいもあってか）、アプリのプロセスを削除した状態から通知をタップする経路で、`Initialize`メソッドで一度`ContactedNotifyPage`が表示された後にSphashPageが終わってHomeが表示される（ContactedNotifyPageを隠してしまう）という状態になりました。

2021-08-18 14:24 UTC, kazuhiro4949 commented
うあ、すいません。昨日コードをきれいにするために色々いじっていたら壊してしまいました。ちょっと一回前の状態に戻します

2021-08-18 15:17 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +                    _ = await NavigationService.NavigateAsync("/" + nameof(MenuPage) + "/" + nameof(NavigationPage) + "/" + nameof(HomePage) + "/" + nameof(ContactedNotifyPage));
> ここはSplashPageにParamsを付けて呼ぶようにした方がシンプルだと思います（ユーザーは通知をタップすると必ずスプラッシュページを見ることになりますが）。

うーんなんかユーザー体験的には微妙な気もしますが、コード的にはシンプルになりますね

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +        ContactPage
ContactedNotifyPageへ変更しようと思います

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +        private DeepLinkDestination? destination;
こちらは不要なプロパティなので削除しました

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +        }
不要な差分が入っていたので削除します

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> -            INavigationResult result = await NavigationService.NavigateAsync("/" + nameof(SplashPage));
直します

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +                param.Add("destination", destination);
SplashPageViewModelに移します

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs
>                  else
あーそうですね。HomePageを追加しようと思います

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            };
経路的には停止状態からの起動・バックグラウンドからの復帰・フォアグラウンドにいる時の3パターンが有ります。遷移周り整理して実装的にはFinishedLaunchingでのAppの初期化でかならずHomePageへ遷移するようにした上で、
FinishedLaunchingで登録したSplashViewModelからの遷移で、すべての通知からの画面遷移を取り扱うようにしました。
起動時にHomePageに行きつつ通知からのタップで連続でContactNotifyPageへナビゲートして大丈夫かな？と思って細かく制御していましたが、やってみたら特に画面遷移とかなく単純に切り替わるだけだったのでそのやり方で行こうと思います

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            notificationCenterDelegate.OnRecieved += (UserNotificationCenterDelegate sender, UNNotificationResponse response) => {
修正します

2021-08-18 15:41 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +        private UserNotificationCenterDelegate notificationCenterDelegate = new UserNotificationCenterDelegate();
修正します

2021-08-18 15:42 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +                    _ = await NavigationService.NavigateAsync("/" + nameof(MenuPage) + "/" + nameof(NavigationPage) + "/" + nameof(HomePage) + "/" + nameof(ContactedNotifyPage));
やってみたところSplash画面表示されなさそう？だったので特に問題なさそうです

2021-08-18 15:45 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
> +                    _ = await NavigationService.NavigateAsync("/" + nameof(MenuPage) + "/" + nameof(NavigationPage) + "/" + nameof(HomePage) + "/" + nameof(ContactedNotifyPage));
まあ一瞬だからそこまで気にすることもないかな。一旦必ずSplash通る形で行ってみますmm

2021-08-18 16:04 UTC, kazuhiro4949 commented on Covid19Radar/Covid19Radar/App.xaml.cs
>              LogUnobservedTaskExceptions();
これってなんのために用意していたやつなんですかね？

2021-08-18 16:39 UTC, kazuhiro4949 commented
@keiji もろもろ修正しました

2021-08-18 17:09 UTC, keiji commented
@kazuhiro4949 ありがとうございます。午前中に見ますね！

2021-08-19 02:54 UTC, keiji reviewed
ありがとうございます。良い感じに動くことを確認しました！

動作とは関係ない細かい指摘が多いですが、対応検討お願いします。

2021-08-19 02:54 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +using Covid19Radar;
このusing使っていないので削除して大丈夫です。

2021-08-19 02:54 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            var prismApp = new App();
ぼくのレビュー内容が不完全で申し訳ないです。

ここでインスタンス化せず下のLoadApplicationの手前で`_prismApp`に代入した方がすっきりすると思います（`OnRecieved `のイベントは初期化後に呼ばれるので）。

2021-08-19 02:54 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/AppDelegate.cs
> +            _prismApp = prismApp;
ここで次のようにしてしまいましょう。

```
_prismApp = new App();
LoadApplication(_prismApp);
```

2021-08-19 02:54 UTC, keiji commented on Covid19Radar/Covid19Radar/Views/HomePage/SplashPage.xaml.cs
> +        }
👍 

呼び出しは`SplashPage`で、ハンドリングは`SplashPageViewModel`なので、`DeepLinkDestinationKey`のアクセススコープがprivateにならないんですね……理解しました。

2021-08-19 02:54 UTC, keiji commented on Covid19Radar/Covid19Radar/Views/HomePage/SplashPage.xaml.cs
> +        public static string DeepLinkDestinationKey = "destination";
`const`を付けて定数にしてください。

```
public const string DeepLinkDestinationKey = "destination";
```

2021-08-21 08:08 UTC, kazuhiro4949 commented
@keiji 修正しましたmm

2021-08-23 02:13 UTC, keiji approved these changes
LGTM!

2021-08-23 03:19 UTC, merged