開発中のカプチーノ版COCOAでENを有効化しなかった時に先に進まない問題修正
cocoa-mhlw/cocoa pull request #342
Opened 2021-08-29 15:21 UTC by kazuhiro4949

## Issue 番号 / Issue ID

- Close #329

## 目的 / Purpose

- チュートリアルにてをENの許諾を許可しなかったときに一瞬固まるという問題だと思って調査をしていたのですが、何も触らずに待っていると先に進まないことがわかりました
- また、ENの許諾をスキップした時に「アプリを再インストールするか〜」のアラートも出なくなっていました
- 原因はAbsExposureNotificationApiServiceのStartExposureNotificationAsync()で例外発生時にそこから処理が進まなかったためでした
- StartAsync()で例外発生(?)がしている時にcatchをつけて先に進めることで最終的にどのルートでもreturn trueをするように修正しました

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request の種類 / Pull Request type

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test
- iOSアプリでCOCOA2を初回起動
- チュートリアルを進めて、接触確認の許諾アラートを出す
- 許諾を許可しない

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```
entitlementsをつかったDEBUGビルド
```

## 確認事項 / What to check

- returnはtrueで大丈夫か
- boolを返す必要があるか
- 非同期通信内でのtry-catchの使い方などC#の実装として問題ないか

## その他 / Other information

2021-08-29 23:45 UTC, keiji requested changes
Exceptionをここで握りつぶすと、どのような理由で失敗したかUI側からわからなくなります。`TutorialPage6ViewModel`と`HomePageViewModel`で`ENException`をcatchして、挙動を分けるのが良いと思います。

2021-08-30 13:54 UTC, kazuhiro4949 commented
@keiji 正しい動きを理解できていないのですが、TutorialPage6ViewModelとHomePageViewModelでENExceptionをcatchして挙動を分けることでどういったことを実現するイメージでしょうか？？
現状のcocoa2の実装が例外をキャッチして特になにかしているわけではないと思いますが、追加する挙動がわかっていないです。

2021-08-30 14:45 UTC, kazuhiro4949 commented
挙動に関する詳細の話をこちらで確認しましたmm 何かしらの案内を出したほうがいいということですね。
https://github.com/cocoa-mhlw/cocoa/issues/329#issuecomment-907902511

iOSのCOCOAでは許諾していない場合にはHomePage表示時にアラートを出して、”OSの許諾をオンにしてください"という案内をすでに出していて、とりあえずはそれでいいかと思っていますが別のアラートにしたほうがいいじゃないかということですかね？
その場合、動くようにしたやつで動作を見つつ別途Issueで対応を検討するで良いかと思いました。

2021-08-31 15:45 UTC, keiji commented
いまのCOCOA2（iOS）だと例外を受け取ったときにハンドリングしてアラートをだしていない状況と理解しています。

HomePageViewの該当個所から例外発生時にiOSのUnauthorizedのコードが返ったときだけアラート出すように調整お願いできますか。

その他のコードついてはまた状態を拾いながら別途対応していきましょう。

2021-09-01 00:38 UTC, kazuhiro4949 commented
@keiji HomePageViewでStartExposureNotificationAsyncが呼ばれるときに例外のハンドリングはしていないですが、COCOA2ではその後にステータスの確認をして状態に合わせてアラートを出しているかと思います。

https://github.com/kazuhiro4949/cocoa/blob/feature/cocoa2_startnotification_return/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs#L96

![IMG_B8FE2FD2B085-1](https://user-images.githubusercontent.com/18320004/131592874-c57fa508-10fd-4a27-94f9-1a98c46695fc.jpeg)

一旦はこれでいいじゃなかという意見ですが、これは出さずに別のアラートを出したほうがいいもしくは他にもアラートを出したほうがいいという話でしょうか？

2021-09-01 00:40 UTC, keiji commented
承知しました。では現状のままでいきましょう。
エラーハンドリングについては引き続き仕様案を作りたいですね。よくわからないエラーコードもあるので…

2021-09-01 00:41 UTC, keiji commented
`TutorialPage6ViewModel`についても同様としますか？　こちらはユーザーが許諾をしなくてもとりあえずホーム画面に進むというCOCOA1系の挙動に合わせるのが親切かなと思いますが。

2021-09-01 13:16 UTC, kazuhiro4949 commented
@keiji TutorialPage6ViewModelからホームへ遷移するときも同様の動作です。
とりあえずこのプルリクでは動いてない部分を治すところに絞って、
ENの状態に応じたハンドリングに関しては別の複数のissueにして処理したほうが良さそうと思っています。
(プルリクの単位・生存期間はできるだけ小さいほうがいいため)

2021-09-01 13:21 UTC, keiji commented
ありがとうございます。そうですね。生存期間をなるべく短くに賛成です。

このPullRequestでは利用者がENの利用を許諾しなかったときにチュートリアルが次の画面に自動で遷移しない。と言う課題を修正すると言うことで認識はあっていますか？

2021-09-01 13:23 UTC, kazuhiro4949 commented
@keiji あ、いや、チュートリアルは通常通り遷移します。
HomePageViewModelへ遷移したときにここと同じ動きをしてアラートが表示されます。

https://github.com/cocoa-mhlw/cocoa/pull/342#issuecomment-909761852

2021-09-01 13:26 UTC, kazuhiro4949 commented
@keiji すいません、↑で削除したコメントに関しては質問内容を誤読していました。
プルリクの内容はそれであっています

2021-09-01 13:33 UTC, keiji commented
ちょっと話を整理させてください。
今回のIssueの主題はチュートリアルが（タッチしなければ）先に進まないと言う話だったと記憶してます。この問題は存在すると言うことでいいでしょうか（通常通り遷移するとのことで混乱しています）。

また、このPullRequestのやり方（Exceptionを取ってreturnに置き換える）では対応として十分ではないので、チュートリアルViewModelでExceptionをcatchして対応する必要があるという認識です。

このPullRequestが今後そのように調整されるということで良かったですか？

2021-09-01 14:53 UTC, keiji commented
@kazuhiro4949 
`AbsExposureNotificationApiService`はENに最も近いコンポーネントなので、ここでExceptionをcatchして捨ててしまうのは影響が大きいと考えます。

いくつかあるExposure Notifications APIの中でこれだけがExceptionをthrowしないのは混乱を招く可能性があります。また、今回のこの方策を選んだとして、後々、View側で細かく表示を出し分けるときにはExceptionのエラーコードが必要になるわけですが、そこでふたたびExceptionを捨てずにthrowするように戻すと、今度はそのときにAPIを利用している箇所すべてで対応が必要になるので、確認も含めた手戻りが大きくなると考えます。

Exceptionを捨てるというのは、捨てなければやりようがないないときの最後の手段だと考えています（またはExceptionを返さなくてもいい仕組みを作るか）。

今回の場合、該当するViewModelでなるべく細かい単位（今回であれば`ENException`）でcatchするようにしてください。

2021-09-01 15:10 UTC, kazuhiro4949 commented
@keiji 「後々View側で細かく表示を出し分ける」というのは具体的にはどういう内容でしょうか？
その作業ををやる前にエラーのハンドリング方法を決めて実装する、決めるよりも先に作るので早く対応させたい場合はこのプルリクとは別プルリクとしてやる、でいいと思います。
また、"そこでふたたびExceptionを捨てずにthrowするように戻す"わけではなく、もともと拾ってないためここで対応することでなにか手戻りが発生するわけではないです。
この問題はこの問題として対応するのではなく複数の課題をまとめて扱う必要性がちょっとピンときていません。

2021-09-01 15:36 UTC, keiji commented
@kazuhiro4949 
ぼくがうまく説明できておらず、お手数をかけて申し訳ない。改めて説明します。

チュートリアルで接触確認APIを有効にしているのは`TutorialPage4ViewModel`の次の箇所だと認識しています。

https://github.com/cocoa-mhlw/cocoa/blob/ccc3cb8d5a7e45c68416b624d7263dc58160bda7/Covid19Radar/Covid19Radar/ViewModels/Tutorial/TutorialPage4ViewModel.cs#L33-L45

ご覧の通り、`ENException`はcatchしています。catchしてログに記録するだけで何もしていません。`StartExposureNotificationAsync`を実行して利用者に拒絶されると`ENException`がthrowされます。コードでは例外をcatchしているけど何もしていないので、`NavigationService.NavigateAsync(nameof(TutorialPage6));`が実行されないのが問題が発生している言です。

これを次のようにすれば、ENExceptionをcatchした上で次の画面に進むことができるので、今回はそうして欲しいと言うのがぼくの言いたいことなのです。

```
            try
            {
                await exposureNotificationApiService.StartExposureNotificationAsync();
                await NavigationService.NavigateAsync(nameof(TutorialPage6));
            }
            catch (ENException exception)
            {
                loggerService.Exception("ENException", exception);
                await NavigationService.NavigateAsync(nameof(TutorialPage6));
            }
            finally
            {
                loggerService.EndMethod();
            }
```

@kazuhiro4949 さんの仰るようにENExceptionのコードでアラートを出したりすることは別の問題です。

一方、`StartExposureNotificationAsync`からthrowされるENExceptionをどのように扱うかは、この課題に関係することなので、課題の解決は`AbsExposureNotificationApiService`ではなく`TutorialPage4ViewModel`でやって欲しいです。

2021-09-01 15:57 UTC, kazuhiro4949 commented
@keiji なるほどです。コードありがとうございます。
僕としてはそういった修正も含め必要なフェーズで後々実装するでもよいんじゃないかなと思っておりました。(cocoa2へのプルリクは一つ一つのプルリクで完成した状態や設計を目指さずにとりあえず通してちゃんと動く状態にしてそこから仕様も合わせて詰めていくという認識のため)
ただ確かにその実装であればそこまで修正コストがかかりそうでもないのと話が若干平行線にもなってきたので、その対応を入れるという結論で行きますmm

2021-09-02 14:18 UTC, kazuhiro4949 commented
@keiji ViewModelのException内で後続処理を実行するよう変更しました

2021-09-02 16:47 UTC, keiji approved these changes
LGTM!

2021-09-02 16:48 UTC, merged