第1期コードレビュー用
cocoa-mhlw/cocoa pull request #573
Opened 2021-12-07 02:36 UTC by keiji

## Issue 番号 / Issue ID

- #300

## 目的 / Purpose

- COCOA2のコードレビューを始めるに当たって、第1期分をここにまとめる

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request の種類 / Pull Request type

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```

```

## 確認事項 / What to check

-

## その他 / Other information

2021-12-07 08:19 UTC, cocoa-dev005 requested changes

2021-12-07 08:19 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +      - '.github/**'
[質問]
`'.github/workflows/CI.yml'` があるのに `'.github/**'` を指定している理由は何でしょうか？
もし他のワークフローの変更時も GitHub Actions を実行したいのでしたら `'.github/workflows/**'` でもいいと思いました。
どちらにしろ冗長なので片方は削除すべきです。

2021-12-07 08:19 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +      - '.github/**'
`pull_request:` や `CIserver.yml` についても同様です。

2021-12-07 08:19 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +    runs-on: macos-latest # Tests must be executed on macos
[修正任意]
なぜ macOS でテストを実行しなければいけないのかの理由（why）もコメントに書くと親切です。

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
> +      <Version>19.7.2-eap-alpha03</Version>
[質問]
アルファ版のライブラリが使われていますが、プロダクトコードで使用して問題ありませんか？

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
> +using Xamarin.Essentials;
[修正任意]
`Xamarin.Essentials` を呼び出すとサービスの単体テストが書きづらくなるので、できる限り外から注入すべきです。
単体テストが書きづらくならなければ問題ありません。

```suggestion
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.Android/Services/ExposureNotificationApiService.cs
> +using Xamarin.Essentials;
[修正任意]
`Xamarin.Essentials` を呼び出すとサービスの単体テストが書きづらくなるので、できる限り外から注入すべきです。
単体テストが書きづらくならなければ問題ありません。

```suggestion
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +using Xamarin.Essentials;
[修正任意]
`Xamarin.Essentials` を呼び出すとサービスの単体テストが書きづらくなるので、できる限り外から注入すべきです。
単体テストが書きづらくならなければ問題ありません。

```suggestion
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
> +            PeriodicWorkRequest periodicWorkRequest = CreatePeriodicWorkRequest();
[修正任意]
型推論できそうです。

```suggestion
            var workManager = WorkManager.GetInstance(Platform.AppContext);

            var periodicWorkRequest = CreatePeriodicWorkRequest();
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
> +      <Version>1.2.3-alpha01</Version>
[質問]
アルファ版のライブラリが使われていますが、プロダクトコードで使用して問題ありませんか？

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +            _loggerService.Debug($"BGTASK_IDENTIFIER: {BGTASK_IDENTIFIER}");
[修正任意]
こちらは固定値なので不要そうです。

```suggestion
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                            .Count() != 0;
このパターンは `.Any()` を使うべきです。

```suggestion
                            .Any(status => status.Code == ExposureNotificationStatus.Code_iOS.Unauthorized);
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                            _loggerService.Error("Exposure notofication is not authorized.");
typo

```suggestion
                            _loggerService.Error("Exposure notification is not authorized.");
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                        bool isUnauthorized = statuses
[修正任意]
型推論できます。

```suggestion
                        var isUnauthorized = statuses
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                BGProcessingTaskRequest bgTaskRequest = new BGProcessingTaskRequest(BGTASK_IDENTIFIER)
[修正任意]
型推論できます。

```suggestion
                var bgTaskRequest = new BGProcessingTaskRequest(BGTASK_IDENTIFIER)
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                    NSErrorException exception = new NSErrorException(error);
[修正任意]
型推論できます。

```suggestion
                    var exception = new NSErrorException(error);
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureNotificationApiService.cs
> +            }
[修正任意]
アロー演算子を使うとスッキリ書けます。

```suggestion
            set => _exposureNotificationClient.UserExplanation = value;
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureNotificationApiService.cs
> +            }
[修正任意]
アロー演算子を使うとスッキリ書けます。

```suggestion
            set => _exposureNotificationClient.IsTest = value;
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Common/TemporaryExposureKeyUtils.cs
> +            List<TemporaryExposureKey> filteredTemporaryExposureKeys = new List<TemporaryExposureKey>();
[修正任意]
型推論できます。

```suggestion
            var filteredTemporaryExposureKeys = new List<TemporaryExposureKey>();
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> +        public static string CombineAsUrl(params string[] paths)
[質問]
標準の `Path.Combine()` メソッドを使わずに自前でメソッドを用意している理由は何でしょうか？
Xamarin.Forms ではないと思いますが、プラットフォームによって区切り文字が異なることがあるので、できる限り標準のメソッドを使うべきだと思います。

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> +            if (paths is null)
[修正任意]
配列が空の場合もリターンしていいと思います。

```suggestion
            if (paths is null || paths.Length == 0)
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Extensions.cs
> +        public static int ToEnInterval(this DateTime dateTime)
[修正任意]
メソッド名の末尾に時間の単位を付けるとわかりやすいです。

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +        private const long BUFFER_LENGTH = 4 * 1024 * 1024;
[修正任意]
変数名の末尾に単位を付けるとわかりやすいです。

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +            HttpResponseMessage response = await _client.GetAsync(url, cancellationToken);
[修正任意]
型推論できます。

```suggestion
            var response = await _client.GetAsync(url, cancellationToken);
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +                string content = await response.Content.ReadAsStringAsync();
[修正任意]
型推論できます。

```suggestion
                var content = await response.Content.ReadAsStringAsync();
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +                int len = 0;
[修正任意]
型推論できます。

```suggestion
            var uri = new Uri(diagnosisKeyEntry.Url);
            var response = await _client.GetAsync(uri, cancellationToken);
            if (response.IsSuccessStatusCode)
            {
                var fileName = uri.Segments[uri.Segments.Length - 1];
                var outputPath = Path.Combine(outputDir, fileName);

                var buffer = new byte[BUFFER_LENGTH];

                using var bs = new BufferedStream(await response.Content.ReadAsStreamAsync());
                using var fs = File.OpenWrite(outputPath);

                var len = 0;
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +                throw new HttpRequestException($"Request is unsuccessful with status code {response.StatusCode}");
[修正任意]
`unsuccessful` より `failed` のほうが一般的だと思いました。

```suggestion
                throw new HttpRequestException($"Request is failed with status code {response.StatusCode}");
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2244" />
[質問]
`Xamarin.Forms` をメジャーバージョンアップしていますが、こちらは ENv2 対応に必須でしょうか？
そうでない場合、何かあったときに問題を切り分けやすくするため、別の PR に分けてほしいです。
同タイミングでリリースすること自体は賛成です。

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +        public void SetDiagnosisKeysDataMappingConfigurationUpdated(bool updated);
`bool` の変数名は先頭に `is` などの適切なプリフィクスを付けてほしいです。

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                    string exposureConfigurationAsJson = await LoadAsync(_currentExposureConfigurationPath);
[修正任意]
型推論できます。

```suggestion
                    var exposureConfigurationAsJson = await LoadAsync(_currentExposureConfigurationPath);
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            string url = _serverConfigurationRepository.ExposureConfigurationUrl;
[修正任意]
型推論できます。

```suggestion
            var url = _serverConfigurationRepository.ExposureConfigurationUrl;
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                string exposureConfigurationAsJson = await response.Content.ReadAsStringAsync();
[修正任意]
型推論できます。

```suggestion
                var exposureConfigurationAsJson = await response.Content.ReadAsStringAsync();
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            string tmpFilePath = Path.Combine(_configDir, Guid.NewGuid().ToString());
[修正任意]
型推論できます。

```suggestion
            var tmpFilePath = Path.Combine(_configDir, Guid.NewGuid().ToString());
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            string tmpFilePath = Path.Combine(_configDir, Guid.NewGuid().ToString());
[修正任意]
型推論できます。

```suggestion
            var tmpFilePath = Path.Combine(_configDir, Guid.NewGuid().ToString());
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            DateTime appliedDate = GetDiagnosisKeysDataMappingConfigurationAppliedDateTime();
[修正任意]
型推論できます。

```suggestion
            var appliedDate = GetDiagnosisKeysDataMappingConfigurationAppliedDateTime();
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            DateTime downloadedDate = GetExposureConfigurationDownloadedDateTime();
[修正任意]
型推論できます。

```suggestion
            var downloadedDate = GetExposureConfigurationDownloadedDateTime();
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                long epoch = _preferencesService.GetValue(PreferenceKey.ExposureConfigurationDownloadedEpoch, 0L);
[修正任意]
型推論できます。

```suggestion
                var epoch = _preferencesService.GetValue(PreferenceKey.ExposureConfigurationDownloadedEpoch, 0L);
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                long epoch = _preferencesService.GetValue(PreferenceKey.ExposureConfigurationAppliedEpoch, 0L);
[修正任意]
型推論できます。

```suggestion
                var epoch = _preferencesService.GetValue(PreferenceKey.ExposureConfigurationAppliedEpoch, 0L);
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                        return currentExposureConfiguration;
`_loggerService.EndMethod();` を呼び出してからリターンすべきです。

```suggestion
                        _loggerService.EndMethod();
                        return currentExposureConfiguration;
```

2021-12-07 08:19 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                return currentExposureConfiguration;
`_loggerService.EndMethod();` を呼び出してからリターンすべきです。

```suggestion
                _loggerService.EndMethod();
                return currentExposureConfiguration;
```

2021-12-07 09:11 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
> +      <Version>19.7.2-eap-alpha03</Version>
問題ないという認識です。
`alpha03`は、ぼくが勝手につけた名前で、alphaをbetaにしたりは勝手にできますが、それをしたから何が変わるものでもありません。

元々「Xamarin.GooglePlayServices.Nearby.ExposureNotification」自体が無保証のオープンソースライブラリと認識していますし、さらに言えば、元々のライブラリもEAP（Early Access Program）なので、そういう意味では「プロダクトに使うぞ」と言う強い気持ちがあるかないかの問題と思います。

2021-12-07 09:12 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
> +      <Version>1.2.3-alpha01</Version>
こちらも同様に、問題ないという認識です。
`alpha01`は、ぼくが勝手につけた名前で、alphaをbetaにしたりは勝手にできますが、それをしたから何が変わるものでもありません。

元々「Xamarin.iOS.ExposureNotification」自体が無保証のオープンソースライブラリと認識しています。「プロダクトに使うぞ」と言う強い気持ちで使います。

2021-12-07 09:18 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
> +using Xamarin.Essentials;
これXamarin.Essentialsを使っているのは`Platform.AppContext`でContextを取る部分ですね。
ここは本当にAndroidプラットフォーム固有の部分なので外部注入には適さないと考えています。

実際、テストでは`AbsExposureDetectionBackgroundService`自体をモック化して、`Schedule`メソッドは何も書かないということをしているという認識です。

2021-12-07 09:21 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +using Xamarin.Essentials;
こちら`AppInfo.PackageName`を取る部分ですね。こちらも同様に完全にiOS Specificな部分で、テスト対象は`ExposureDetectionBackgroundService`ではなく、`AbsExposureDetectionBackgroundService`をモック化して行うのが適切と考えています。

2021-12-07 09:26 UTC, keiji commented on Covid19Radar/Covid19Radar/Extensions.cs
> +        public static int ToEnInterval(this DateTime dateTime)
これは`ENInterval`という単位なのです。

2021-12-07 09:29 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +        private const long BUFFER_LENGTH = 4 * 1024 * 1024;
一般的にはBuffer用途でByte単位の時は単位つけない認識なので、このままで行きたいです。

Bytesじゃない場合、例えばBufferMibとかなら書いた方がいいかも。

2021-12-07 09:31 UTC, keiji commented on Covid19Radar/Covid19Radar/Covid19Radar.csproj
> +    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2244" />
これはCOCOA2のPull Requestなので、ENv2にこだわらず、できることはやっていきたいと考えています。

問題の切り分けという意味では、リグレッションテストで拾いましょう。

2021-12-07 09:32 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +        public void SetDiagnosisKeysDataMappingConfigurationUpdated(bool updated);
Isをつけるのはメソッド引数`updated`にでしょうか。それともSetterでしょうか。

個人的には`SetIs...`という書き方はあまりしない方がいいかなと思っています。

2021-12-07 09:34 UTC, keiji commented
ひとまずレビューいただいた内容で対応箇所の取り込みを行います。

一方、型推論については別途コメントさせてくださいー。

2021-12-07 10:01 UTC, keiji commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> +        public static string CombineAsUrl(params string[] paths)
`Path.Combine`だと`paths`の要素文字列の最初に`/`があると想定通りに動かず、trailing slashなURLをうまく扱えなかったからと記憶しています。

```
		var path = Path.Combine("/a", "/b");     // path = "/"
```

一方で、この処理をUtilsというざっくりしたクラスに置くのは良くないなと思うのに加えて、意図がわかりやすいように（Path.Combineでは対応できないケースに対応するため）テストケースを書いて置いた方がいいですね。

こちら対応します。

2021-12-07 10:15 UTC, keiji commented
@cocoa-dev005 
型推論について質問というか、意識あわせをしておきたいと思っています。現時点では型推論を使う使わないという点については明確なコード規約のようなものがないと認識しています。

個人的に自分の傾向を考え直してみると「型が書けるところは、どんどん書いてしまえばいい」としています。一方で、Listとかforeachの中とかジェネリクスが絡むところは積極的に型推論を使って楽していこうという方針のようです。
「ようです」というのは、指摘を受けるまで自分がどう型推論を使っているのか意識していなかったからですが……。

[Microsoftのコーディング規約](https://docs.microsoft.com/ja-jp/dotnet/csharp/fundamentals/coding-style/coding-conventions#language-guidelines)を紐解くと、

> 割り当ての右側から型が明らかではない場合、var を使用しないでください。 メソッド名から型が明らかであると想定しないでください。 変数の型は、new 演算子または明示的なキャストの場合に明らかであると見なされます。

として、メソッドの結果などを受け取るときはvarは使わないという記述もあります（Microsoftのコード規約に準じると決めていないので、あくまで参考情報です）。

型推論をどう扱っていくかは今後の検討事項として、このPull Requestでは対応せずとさせていただけるとありがたいです。
やるときはこのPull Requestの範疇を超えて、すべてのコードを対象にやってしまいましょう（できればNonNull/Nullable対応もやりたいなぁ）。

----

ちなみに、ぼくはKotlinのような型が後置の言語では、積極的に型推論を使っていますね。やはり言語仕様に手軽に最大入夫化にできる`val`があるのは強いです。

2021-12-07 10:29 UTC, keiji commented on Covid19Radar/Covid19Radar.Android/Services/ExposureNotificationApiService.cs
> +using Xamarin.Essentials;
こちらも同様にXamarin.Essentialsを使っているのはPlatform.CurrentActivityでActivityを取っている部分ですね。
ここは本当にAndroidプラットフォーム固有の部分なので外部注入には適さないと考えています。

実際、テストではAbsExposureNotificationApiService自体をモック化して、プラットフォーム依存のところを避けてテストするという理解でいます。

2021-12-07 10:32 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +        public void SetDiagnosisKeysDataMappingConfigurationUpdated(bool updated);
`setIs...` あるな……うーん。

https://developer.android.com/reference/kotlin/androidx/recyclerview/widget/RecyclerView.ViewHolder#setisrecyclable

2021-12-07 10:39 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                return currentExposureConfiguration;
6a3cbf0 で対応しました！

2021-12-07 10:39 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                        return currentExposureConfiguration;
6a3cbf0 で対応しました！

2021-12-07 10:39 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                            .Count() != 0;
6a3cbf0 で対応しました！

2021-12-07 10:39 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                            _loggerService.Error("Exposure notofication is not authorized.");
6a3cbf0 で対応しました！

2021-12-07 10:39 UTC, keiji commented on .github/workflows/CI.yml
> +    runs-on: macos-latest # Tests must be executed on macos
6a3cbf0 で対応しました！

2021-12-07 10:39 UTC, keiji commented on .github/workflows/CI.yml
> +      - '.github/**'
6a3cbf0 で対応しました！

2021-12-07 10:40 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +            _loggerService.Debug($"BGTASK_IDENTIFIER: {BGTASK_IDENTIFIER}");
6a3cbf0 で対応しました！

2021-12-07 10:40 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureNotificationApiService.cs
> +            }
6a3cbf0 で対応しました！

2021-12-07 10:40 UTC, keiji commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureNotificationApiService.cs
> +            }
6a3cbf0 で対応しました！

2021-12-07 10:46 UTC, keiji commented
@cocoa-dev005 
指摘いただいた箇所は型推論と`CombineAsUrl`を除いて 6a3cbf0 に入れました（個別にSuggestionしていただいていたのに恐縮です）。

`CombineAsUrl`については少し大きな変更になるので別コミットにします。
準備ができたらもう一度Reivewリクエストします。

2021-12-07 11:16 UTC, keiji commented
@cocoa-dev005 
ecbf275 このコミットのテストを参照してもらうとPath.Combineとの違いがわかりやすいと思います。
当該箇所は（デバッグモードですが）ユーザーが入力する可能性がある部分なので、先頭または最後の `/` の有無値が保証されておらず、Path.Combineだと期待した値にならないことがあるので、URL用の独自メソッドを作っています。

標準関数でこれ使ったらいいよ。みたいなのがあったら教えてもらえると助かります。

2021-12-08 00:40 UTC, keiji commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> +        public static string CombineAsUrl(params string[] paths)
ecbf275 で対応しました。

2021-12-08 00:43 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +        public void SetDiagnosisKeysDataMappingConfigurationUpdated(bool updated);
6a3cbf0 で対応しました！

2021-12-08 02:42 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj
> +      <Version>19.7.2-eap-alpha03</Version>
なるほど、OSS をそのまま使うのではなくプロジェクトに取り込んでいるのですね。
勘違いしました。問題ありません。

2021-12-08 02:43 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
> +using Xamarin.Essentials;
承知しました。
指摘では省略してしまいましたが、外部注入に適さない場合も当然問題ありません。

2021-12-08 02:43 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.Android/Services/ExposureNotificationApiService.cs
> +using Xamarin.Essentials;
こちらも他と同様に問題ありません。

2021-12-08 02:44 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +using Xamarin.Essentials;
こちらも他と同様に問題ありません。

2021-12-08 02:45 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Covid19Radar.iOS.csproj
> +      <Version>1.2.3-alpha01</Version>
こちらも他と同様に問題ありません。

2021-12-08 02:48 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Extensions.cs
> +        public static int ToEnInterval(this DateTime dateTime)
なるほど、失礼しました…。

2021-12-08 02:49 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +        private const long BUFFER_LENGTH = 4 * 1024 * 1024;
一般的なら問題ありません。
私が勉強不足でした :pray:

2021-12-08 02:51 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +        public void SetDiagnosisKeysDataMappingConfigurationUpdated(bool updated);
あ、メソッド引数 `updated` のみのつもりでした！
メソッド名までは見ていませんでしたが、この対応で問題ないと思います。

2021-12-08 03:00 UTC, cocoa-dev005 commented
@keiji 
型推論については私が公式のコーディング規約を把握していませんでした…。（Swift や Kotlin の考えで指摘してしまいました）
仰る通りそもそも方針を決めていないので、この PR では対応しなくて問題ありません。
指摘もノイズになるのですべてクローズします :bow:

私も NonNull/Nullable 対応したいです…。

2021-12-08 03:03 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.Android/Services/ExposureDetectionBackgroundService.cs
> +            PeriodicWorkRequest periodicWorkRequest = CreatePeriodicWorkRequest();
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:03 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                        bool isUnauthorized = statuses
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:04 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                BGProcessingTaskRequest bgTaskRequest = new BGProcessingTaskRequest(BGTASK_IDENTIFIER)
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。
（ここは `new` していて型が明確なので、型推論したほうがスッキリしますが）

2021-12-08 03:04 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar.iOS/Services/ExposureDetectionBackgroundService.cs
> +                    NSErrorException exception = new NSErrorException(error);
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。
（ここは `new` していて型が明確なので、型推論したほうがスッキリしますが）

2021-12-08 03:04 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Common/TemporaryExposureKeyUtils.cs
> +            List<TemporaryExposureKey> filteredTemporaryExposureKeys = new List<TemporaryExposureKey>();
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。
（ここは `new` していて型が明確なので、型推論したほうがスッキリしますが）

2021-12-08 03:05 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +            HttpResponseMessage response = await _client.GetAsync(url, cancellationToken);
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:06 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +                string content = await response.Content.ReadAsStringAsync();
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:06 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs
> +                int len = 0;
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:06 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            string url = _serverConfigurationRepository.ExposureConfigurationUrl;
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:06 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                string exposureConfigurationAsJson = await response.Content.ReadAsStringAsync();
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:06 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            string tmpFilePath = Path.Combine(_configDir, Guid.NewGuid().ToString());
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:06 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            DateTime appliedDate = GetDiagnosisKeysDataMappingConfigurationAppliedDateTime();
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:07 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            DateTime downloadedDate = GetExposureConfigurationDownloadedDateTime();
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:07 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                long epoch = _preferencesService.GetValue(PreferenceKey.ExposureConfigurationDownloadedEpoch, 0L);
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:07 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                long epoch = _preferencesService.GetValue(PreferenceKey.ExposureConfigurationAppliedEpoch, 0L);
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:07 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +            string tmpFilePath = Path.Combine(_configDir, Guid.NewGuid().ToString());
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:07 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ExposureConfigurationRepository.cs
> +                    string exposureConfigurationAsJson = await LoadAsync(_currentExposureConfigurationPath);
型推論については方針が決まっていないため、本 PR ではどちらでも問題ないこととする。

2021-12-08 03:44 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> +        public static string CombineAsUrl(params string[] paths)
理解しました。テストコードがわかりやすいので理解しやすかったです！

`Combine(String, String)` メソッドの仕様として、2 番目のパスが絶対パスだと結合せずに 2 番目のみ返すとのことです。
ref: https://docs.microsoft.com/ja-jp/dotnet/api/system.io.path.combine?view=net-6.0#System_IO_Path_Combine_System_String_System_String_

先頭のスラッシュがルートと認識され、絶対パスと判定されていると思われます。
メソッドを自前で用意するしかなさそうなので、この対応で問題ありません！

2021-12-08 03:46 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> +        public static string CombineAsUrl(params string[] paths)
`CombineAsUrl()` メソッドの先頭に「 `Path.Combine()` メソッドでは 2 番目の引数の先頭にスラッシュが付いている場合に期待通りに結合されないため、URL の結合は本メソッドを使う。詳細はテストコードを参照」のようなコメントがあると親切です！

2021-12-08 08:47 UTC, cocoa-dev005 requested changes

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        }
[修正任意]
アロー演算子を使うとスッキリ書けます。

```suggestion
        public virtual IList<string> DiagnosisKeyRegisterApiUrls => Regions
            .Select(region => DiagnosisKeyRegisterApiEndpoint.Replace(ServerConfiguration.PLACEHOLDER_REGION, region))
            .Where(url => url != null)
            .Distinct()
            .ToList();
```

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        }
[修正任意]
アロー演算子を使うとスッキリ書けます。

```suggestion
        public virtual IList<string> DiagnosisKeyListProvideServerUrls => Regions
            .Select(region => DiagnosisKeyListProvideServerEndpoint.Replace(ServerConfiguration.PLACEHOLDER_REGION, region))
            .Where(url => url != null)
            .Distinct()
            .ToList();
```

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        }
[修正任意]
アロー演算子を使うとスッキリ書けます。

```suggestion
        public virtual IList<string> ExposureDataCollectServerUrls => Regions
            .Select(region => ExposureDataCollectServerEndpoint?.Replace(ServerConfiguration.PLACEHOLDER_REGION, region))
            .Where(url => url != null)
            .Distinct()
            .ToList();
```

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        public int Version = 1;
[質問]
こちらは具体的に何のバージョンでしょうか？
必要に応じて `AppSettings` に定義してもいいと思いました。

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
> +            await SaveExposureDataAsync(dailySummaryList, exposueWindowList);
`_loggerService.EndMethod();` が呼ばれていません。

```suggestion
            await SaveExposureDataAsync(dailySummaryList, exposueWindowList);
            
            _loggerService.EndMethod();
```

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/DiagnosisKeyRegisterServer.cs
> +            if (random == null)
[修正任意]
null 判定には `is` 演算子が使えます。

```suggestion
            if (random is null)
```

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
> +                    .Count() > 0;
[修正任意]
このパターンは `.Any()` が使えます。

```suggestion
                    .Any(riskLevel => riskLevel >= RiskLevel.High)
```

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        public string ApiUrlBase { get => AppSettings.Instance.ApiUrlBase; }
[修正任意]
スッキリ書けます。

```suggestion
        public string CdnUrlBase => AppSettings.Instance.CdnUrlBase;
        public string ApiUrlBase => AppSettings.Instance.ApiUrlBase;
```

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
> +                if (success)
[修正任意]
真偽型は `is` のプリフィクスを付けたいです。

```suggestion
                var isSuccessful = await exposureNotificationApiService.StartExposureNotificationAsync();
                if (isSuccessful)
```

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/settings.json
> +  "blobStorageContainerName": "diagnosis_keys",
[質問]
`blobStorageContainerName ` の変更は同意が取れていますか？

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Tests/Covid19Radar.UnitTests/AppSettingsTests.cs
> +        [Fact(Skip = "Under consideration")]
[修正任意]
残作業を検索しやすいように `// TODO: ` コメントを付けてほしいです。

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +                Region = "440",
[質問]
モックなので問題なさそうですが、Region が `440` から変更になっているようなので、こちらは変更しなくてもいいのでしょうか？

2021-12-08 08:47 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
> +        // Legacy v1 mode
[質問]
ENv1 モードは残す必要があるのでしょうか？
理由がまだわかっていないので、教えていただきたいです。

2021-12-08 08:49 UTC, cocoa-dev005 commented
@keiji 
全ファイル（テストコードを除く）のレビューが完了しました。ご確認お願いします。

2021-12-08 08:49 UTC, keiji commented on Covid19Radar/Covid19Radar/settings.json
> +  "blobStorageContainerName": "diagnosis_keys",
テスト用の変更が紛れてますね。なおします！

2021-12-08 08:51 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
> +        // Legacy v1 mode
現行バージョンでENv1で発生した接触記録が残ってる人用です

2021-12-08 08:52 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
> +        // Legacy v1 mode
なるほど、理解しました。
ありがとうございます！

2021-12-10 02:06 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
> +#endif
[質問]
`#if DEBUG` でデバッグビルド時に処理を実行しない理由は何でしょうか？
こちらに限らず、デバッグビルドとリリースビルドで挙動を変えるのは望ましくないと考えます。

2021-12-10 14:48 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
> +#endif
ENのテストをするときに、ENを握っているアプリを切り替えると、同じ診断キーで何度も接触確認ができるのですが、COCOAがlastProcessTimestampを保持してフィルターしてしまうといちいちストレージを消去しなければならないので、デバッグの時にはフィルターをかけないようにしています。

ちなみに、デバッグビルドとリリースビルドで、一部の表示や、今回のような複数回実行を防止するガードを付けたり外したりすること。もっと言えば挙動を変えること自体、個人的にはそこまで違和感はありません。
一方、Androidアプリだと同じ事をしようとするとFlavorを作成してソースコードも別になるので、デバッグシンボルの有無でコードにがっつり分岐が書いてあるのはあまり気持ちいいことではありませんね。

デバッグビルドとリリースビルドをどう扱うか（挙動を変えていいか、望ましくないか）については、プロジェクトが定めるポリシーの問題かと思います。たとえばDEBUGはこのように使う。MOCKはこのときに使う。と言うポリシーなどは決まっていますでしょうか。もしあれば教えていただけると助かります。また、GItHubにも掲載できれば、他のコントリビューターにもわかりやすいと思います。

2021-12-10 14:49 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +                Region = "440",
Regionの方を440に戻すので、ここもこのままですね。
ただ、直接書くのは良くないかもしれないのでもう一度見てみます。

2021-12-10 14:51 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        public int Version = 1;
ServerConfiguration自体の書式のバージョンですね。万が一、互換性のない変更があったときにマイグレーションを行えるように作ってあります。
とはいえ、プロダクト版でもファイルに保存するかは未知数ですが、万が一を缶ゲルと、バージョンは入れておいて損はないですね。

2021-12-12 15:27 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +                Region = "440",
eb81000 で一度元に戻しました。

2021-12-12 15:28 UTC, keiji commented on Covid19Radar/Tests/Covid19Radar.UnitTests/AppSettingsTests.cs
> +        [Fact(Skip = "Under consideration")]
eb81000 で対応しました。

2021-12-12 15:28 UTC, keiji commented on Covid19Radar/Covid19Radar/settings.json
> +  "blobStorageContainerName": "diagnosis_keys",
eb81000 で戻しました。

2021-12-12 15:28 UTC, keiji commented on Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs
> +                if (success)
eb81000 で対応しました！

2021-12-12 15:28 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/HttpDataServiceMock.cs
> +        public string ApiUrlBase { get => AppSettings.Instance.ApiUrlBase; }
eb81000 で対応しました！

2021-12-12 15:28 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/DiagnosisKeyRegisterServer.cs
> +            if (random == null)
eb81000 で対応しました！

2021-12-12 15:28 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/ExposureDetectionService.cs
> +                    .Count() > 0;
eb81000 で対応しました！

2021-12-12 15:32 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        }
eb81000 で対応しました。

2021-12-12 15:33 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        }
eb81000 で対応しました。

2021-12-12 15:33 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        }
eb81000 で対応しました。

2021-12-12 15:38 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/UserDataRepository.cs
> +            await SaveExposureDataAsync(dailySummaryList, exposueWindowList);
eb81000 で対応しました。
変更場所の関係で上記コードがOutdatedにならないのですが、次の箇所です。

https://github.com/cocoa-mhlw/cocoa/pull/573/commits/eb81000b47e8ddf4ac0802359a38786f5cde7176#diff-4aa40f83caacf8ecc6d54f0bd417fb05569924a4bf17e4b015e86722708cb74dR186

2021-12-13 03:12 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        public int Version = 1;
書式のバージョンということは、基本的には変更がない、ということですね。
かつリリース時にファイル保存を採用するかも未定とのことなので、このままで問題ありません。
問題があるとわかったときに再考すればいいと思います。

2021-12-13 05:14 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> +        public static string CombineAsUrl(params string[] paths)
@keiji こちらコメントは不要でしょうか？
不要であれば解決にしますね！

2021-12-13 06:57 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        public int Version = 1;
そう考えると、ServerConfigurationが更新されることでバージョンが繰り上がっていくようなイメージを想定するかもしれませんね。

`format_version`とかのほうがいいのかな。ちょっと他のケースでどうしてるのか調べてみます。

2021-12-13 07:06 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        public int Version = 1;
あ、そうですね。ただの `version` よりは `format_version` のほうがわかりやすいです！

ちょっと違うかもしれませんが、他のケースだと Firestore のセキュリティルールは 1 行目に `rules_version = '2';` を書く決まりがあります。
ref: https://firebase.google.com/docs/firestore/security/get-started?hl=ja#security_rules_version_2

2021-12-13 08:25 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
> +#endif
なぜリリースビルド時のみ処理を実行しているかの理由がわかりました。ありがとうございます。

Build Configuration やシンボルを使う際のルールは特に決めていません。
ただ開発チーム内で相談した結果、 `DEBUG` のシンボルを使うと意図がわかりづらく、個別に ON/OFF の切り替えができないので、新たにシンボルを追加してそれを使うほうが望ましいという意見が出ました。

シンボルは「プロジェクトで右クリック > オプション > ビルド > コンパイラ > シンボルの定義」から Build Configuration ごとに追加できます。（Visual Studio for Mac の場合）

2021-12-13 08:26 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
> +#endif
分かりました。EN_DEBUGとかなんかそれっぽい名前で定義します！

2021-12-13 08:28 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
> +#endif
ありがとうございます！

> ENのテストをするときに、ENを握っているアプリを切り替えると、同じ診断キーで何度も接触確認ができるのですが、COCOAがlastProcessTimestampを保持してフィルターしてしまうといちいちストレージを消去しなければならないので、デバッグの時にはフィルターをかけないようにしています。

こちらを要約してコメントに記載してくださるとさらに嬉しいですm(_ _)m

2021-12-14 03:11 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
> +#endif
補足
本来は `#if / #endif` より Conditional Attribute を使うのが望ましいです。
こちらも特にルールを決めておらず、COCOA ではまったく使われていないので今回は対応しなくていいと思いますが、覚えておくと有用です。
ref: https://docs.microsoft.com/ja-jp/dotnet/api/system.diagnostics.conditionalattribute?view=net-6.0

2021-12-14 05:46 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        public int Version = 1;
6ed623b で対応しました。

ルールとは違うので`configuration_version`も考えたのですが、その場合も設定ファイル自体のバージョン（設定ファイルが更新されるとインクリメント）と言う印象を与えてしまうので`format_version`にしました。

ちなみに`format_version`はMinecraftのファイルでも使われているキーのようです

2021-12-14 06:05 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        public int Version = 1;
ご対応ありがとうございます！OK です :)
ルールは違いますよね…例に Firestore を出したのはよくありませんでした、、

2021-12-14 06:16 UTC, keiji commented on Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
> +#endif
20f2d90 で対応しました。`FilterDiagnosisKeysAfterLastProcessTimestamp`メソッドを追加して、そこでフィルターをするようにしています。

当初はFilterDiagnosisKeysAfterLastProcessTimestampにConditional Attributeをつけることで挙動を変えようと考えたのですが、Conditional Attributeは戻り値がvoid型の時にしか使うことができないとのことで、シンプルに`#if / #endif`で分岐することにしました。

戻り値をvoidにして代わりに`ref`をつけた引数を渡したほうがいいとか、C#の流儀でいい感じ解決できる方法があれば教えてもらえるとうれしいです。

2021-12-14 08:21 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Services/AbsExposureDetectionBackgroundService.cs
> +#endif
ご対応ありがとうございます！

C# の流儀はわかりませんが、メソッドに切り出すなら戻り値を `void` にして、参照渡しした変数に代入するほうが可読性が高いと思います。
`#if ... #endif` で分岐するならメソッドに切り出さずに変更前のほうが読みやすいと思います。

とはいえ好みの部分も大きいので解決にします！

2021-12-14 09:21 UTC, cocoa-dev005 commented on Covid19Radar/Covid19Radar/Common/Utils.cs
> +        public static string CombineAsUrl(params string[] paths)
コメント確認しました、OK です！

2021-12-14 09:21 UTC, cocoa-dev005 commented
@keiji LGTM:)
ご対応ありがとうございました！

2021-12-14 10:31 UTC, keiji commented
コンフリクト解決します

2021-12-14 11:32 UTC, keiji commented
`AlertAsync`の第1引数には`message`を指定するのですがリソース名が`Title`となっていました。
修正を含めてあるので 83491c7 を見ておいてください。

2021-12-14 17:26 UTC, keiji commented on Covid19Radar/Covid19Radar/Repository/ServerConfigurationRepository.cs
> +        /// `Path.Combine method` will remove elements before, if any element have `/` as head of string.
```suggestion
        /// `Path.Combine` method will remove elements before, if any element have `/` as head of string.
```

2021-12-16 08:18 UTC, keiji commented
#609 を作ったのでこちらはCloseします。
記録のため 8b3a4b6 に `cocoa2-1st-review` のタグを打ちます。

2021-12-16 08:19 UTC, keiji commented
タグを打ちました。
https://github.com/cocoa-mhlw/cocoa/releases/tag/cocoa2-1st-review

2021-12-16 08:19 UTC, closed without merging