For preventing security incident, Git should ignore settings.json.
cocoa-mhlw/cocoa pull request #866
Opened 2022-02-11 05:49 UTC by keiji

## Issue 番号 / Issue ID

- Close #749

## 目的 / Purpose

もともと`settings.json`は`.gitignore`に指定されている。

https://github.com/cocoa-mhlw/cocoa/blob/c5e480b43779b8dec3f196947c7971f147c51e8f/.gitignore#L383-L385

しかし、.gitignoreに指定するより前のタイミング（Covid19Radar時代）でGitの管理下に置かれた様子。

https://github.com/cocoa-mhlw/cocoa/commit/72c2d4f2d9f83b37404b2fd42bc63858768acf7e#diff-5bdec46c6ceb5e47888fee275ff5ab1440d1abf52b50473c698a6aac3fb14810

https://github.com/cocoa-mhlw/cocoa/commit/7e0910d80b39d730b5e0a61c6c9b99fe6277cfa7

APIキーなどのセンシティブな情報を含むため、誤ってcommitされるのを防ぎたい。

## 破壊的変更をもたらしますか / Does this introduce a breaking change?

```
[x] Yes アプリのビルドに大きな問題はないがCIに影響がある
[ ] No
```

## Pull Request の種類 / Pull Request type

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

## 検証方法 / How to test

### コードの入手 / Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
dotnet restore
```

### コードの検証 / Test the code

```

```

## 確認事項 / What to check

- CI側の対応が必要

## その他 / Other information

2022-02-28 03:17 UTC, cocoa-dev005 requested changes

2022-02-28 03:17 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +      run: cp ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json.sample ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
[修正任意]
CI なのでどちらでも問題ないですが、サンプルファイルを残す必要はないので `cp` でなく `mv` でいいと思いました！

```suggestion
      run: mv -f ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json.sample ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
```

2022-02-28 03:17 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +      run: cp ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json.sample ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
[修正任意]
シンタックスハイライトが効かないなどの理由から、 `settings.json.sample` より `settings_sample.json` のようなファイル名が好みです。

2022-02-28 03:17 UTC, cocoa-dev005 commented on documents/content/docs/development/how_to_build.md
> +```
シンタックスハイライトを付けると、よりわかりやすいです。
ref: https://gohugo.io/content-management/syntax-highlighting/

```suggestion
```json
```

2022-02-28 03:17 UTC, cocoa-dev005 commented on documents/content/docs/development/how_to_build.md
> +|appVersion|アプリのバージョン。CIでの差し替えを想定しているため、手動でのビルドの際は、AndroidManifest.xmlやinfo.plistを書き換える必要があります|
[修正任意]
`settings.json` と同じ並び順のほうがわかりやすいと思います。

2022-02-28 03:17 UTC, cocoa-dev005 commented on documents/content/docs/development/how_to_build.md
> +
[修正任意]
以下の一行があるとより親切です。

```suggestion
大文字のスネークケースで記述されている箇所（`APP_VERSION` など）はアプリ配布時のパイプラインで実際の値に書き換えます。

```

2022-02-28 03:17 UTC, cocoa-dev005 commented on documents/content/docs/development/how_to_build.md
> +|appVersion|アプリのバージョン。CIでの差し替えを想定しているため、手動でのビルドの際は、AndroidManifest.xmlやinfo.plistを書き換える必要があります|
```suggestion
|appVersion|アプリのバージョン。CIでの差し替えを想定しているため、手動でのビルドの際は、AndroidManifest.xmlやInfo.plistを書き換える必要があります|
```

2022-02-28 03:17 UTC, cocoa-dev005 commented on documents/content/docs/development/how_to_build.md
> +|appStoreUrl|AppStoreのURL|
```suggestion
|appStoreUrl|App StoreのURL|
```

2022-02-28 03:18 UTC, cocoa-dev005 commented
@keiji レビューしました！お手数ですがご確認お願いします。
Azure Pipelines のパイプラインも修正が必要になりますが、私たちのほうで別 PR で修正するのがいいでしょうか？

2022-02-28 03:34 UTC, cocoa-dev004 commented on .github/workflows/CI.yml
> +      run: cp ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json.sample ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
@keiji 
編集する際にエディタにJSONとして認識されたほうが都合がいいので拡張子を.jsonにしていただきたいです。

2022-02-28 03:38 UTC, cocoa-dev004 commented on .github/workflows/CI.yml
> +      run: cp ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json.sample ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
あと、sampleだと内容が正式なものなのかどうか曖昧な気がするので、template(でなくても良いですが)とかこれがベースに使われるということがわかるような名前がいいと思います。

2022-02-28 03:56 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +      run: cp ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json.sample ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
確かに、本番でも使うので `sample` の命名はあまりよくないですね。

2022-03-01 01:45 UTC, keiji commented on .github/workflows/CI.yml
> +      run: cp ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json.sample ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
`settings_template.json` にしました！

2022-03-01 01:54 UTC, keiji commented on documents/content/docs/development/how_to_build.md
> +|appVersion|アプリのバージョン。CIでの差し替えを想定しているため、手動でのビルドの際は、AndroidManifest.xmlやinfo.plistを書き換える必要があります|
こちら順番を整理しました。settings_template.jsonとhow_to_build.mdのサンプル、表の並び順を合わせました。

2022-03-01 03:19 UTC, cocoa-dev004 approved these changes

2022-03-01 03:30 UTC, keiji commented
@cocoa-dev005 
> Azure Pipelines のパイプラインも修正が必要になりますが、私たちのほうで別 PR で修正するのがいいでしょうか？
このブランチでやってしまうのがいいと思います。フォークしたリポジトリではなく、オリジナル（cocoa-mhlw/cocoa）のブランチで作業しているので、このブランチに直接pushすることができますので。

2022-03-01 06:12 UTC, cocoa-dev005 requested changes

2022-03-01 06:12 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +      run: cp ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings_template.json ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
```suggestion
      run: mv -f ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings_template.json ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
```

2022-03-01 06:12 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +      run: cp ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings_template.json ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
```suggestion
      run: mv -f ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings_template.json ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
```

2022-03-01 06:13 UTC, cocoa-dev005 commented
@keiji 
> Azure Pipelines のパイプラインも修正が必要になりますが、私たちのほうで別 PR で修正するのがいいでしょうか？
>> このブランチでやってしまうのがいいと思います。フォークしたリポジトリではなく、オリジナル（cocoa-mhlw/cocoa）の>> ブランチで作業しているので、このブランチに直接pushすることができますので。

承知しました。では私のほうでこちらのブランチに直接変更を加えます。

2022-03-01 06:26 UTC, keiji commented on .github/workflows/CI.yml
> +      run: mv -f ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings_template.json ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
```suggestion
      run: mv -Force ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings_template.json ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
```

2022-03-01 06:28 UTC, keiji commented on .github/workflows/CI.yml
> +      run: mv -f ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings_template.json ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
`mv -f`はMac/ubuntuでは通るけど、Windowsだと--Forceにしないといけない。ややこしい。

ちなみにAndroidのビルドをWindowsインスタンスで実行している理由は、インスタンス数の立ち上げ制限が各インスタンスの種別毎に決まっているので、ビルド完了が早くなるとかそういう理由だったと思います。

2022-03-01 06:46 UTC, cocoa-dev005 commented on .github/workflows/CI.yml
> +      run: mv -f ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings_template.json ${{ github.workspace }}/Covid19Radar/Covid19Radar/settings.json
ああ、何も考えずに `mv -f` にしていました、、すみません。

2022-03-01 08:01 UTC, cocoa-dev005 commented
@keiji @cocoa-dev004 
Azure Pipelines のほうも修正しました。
https://github.com/cocoa-mhlw/cocoa/pull/866/commits/9472254193ccc44104f5faad0f47db93c089ddf9

2022-03-01 08:01 UTC, cocoa-dev005 approved these changes

2022-03-01 23:44 UTC, ghost approved these changes

2022-03-01 23:46 UTC, merged